// Include sub-document
// -----------------------------------------------------------------------------

== Wie funktioniert SEO?

Suchmaschinen wie Google und Bing verwenden Bots, um Seiten im Web zu crawlen,
von Seite zu Seite zu gehen, Informationen über diese Seiten zu sammeln und
sie in einen Index aufzunehmen. Stellen Sie sich den Index wie eine riesige
Bibliothek vor, in der ein Bibliothekar ein Buch (oder eine Webseite)
aufrufen kann, damit Sie genau das finden, wonach Sie gerade suchen.

Als Nächstes analysieren Algorithmen die Seiten im Index unter
Berücksichtigung von Hunderten von Ranking-Faktoren oder -Signalen, um zu
bestimmen, in welcher Reihenfolge Seiten in den Suchergebnissen für eine
bestimmte Suchanfrage erscheinen sollen. In unserer Bibliotheksanalogie hat
der Bibliothekar jedes einzelne Buch in der Bibliothek gelesen und kann
Ihnen genau sagen, welches die Antworten auf Ihre Fragen enthält.

Unsere SEO-Erfolgsfaktoren können stellvertretend für Aspekte der User
Experience betrachtet werden. Auf diese Weise schätzen Suchbots genau ein,
wie gut eine Website oder Webseite dem Suchenden das geben kann, wonach
er sucht.

Im Gegensatz zu bezahlten Suchanzeigen können Sie Suchmaschinen nicht bezahlen,
um höhere organische Suchrankings zu erhalten, was bedeutet, dass SEO-Experten
die Arbeit investieren müssen.

Unser Periodensystem der SEO-Faktoren organisiert die Faktoren in sechs
Hauptkategorien und Gewichtungen, jede basierend auf ihrer allgemeinen
Bedeutung für SEO. Beispielsweise sind Inhaltsqualität und Keyword-Recherche
Schlüsselfaktoren der Inhaltsoptimierung, und Crawlbarkeit und Geschwindigkeit
sind wichtige Faktoren der Website-Architektur.

Das neu aktualisierte SEO-Periodensystem enthält auch eine Liste von Toxinen,
die von SEO Best Practices ablenken. Dies sind Abkürzungen oder Tricks, die
in Zeiten, als die Methoden der Engines noch viel weniger ausgefeilt waren,
möglicherweise ausreichten, um ein hohes Ranking zu garantieren. Und vielleicht
funktionieren sie jetzt sogar für kurze Zeit. Zumindest bis Sie erwischt werden.

Wir haben auch einen brandneuen Nischenbereich, der tief in die Erfolgsfaktoren
des SEO hinter drei Schlüsselnischen eintaucht: Lokales SEO, News/Publishing
und E-Commerce-SEO. Während unser gesamtes SEO-Periodensystem Ihnen mit den
besten Praktiken helfen wird, kann Ihnen die Kenntnis der SEO-Nuancen für
jede dieser Nischen helfen, in den Suchergebnissen für Ihr kleines
Unternehmen, Ihren Rezept-Blog und/oder Ihren Online-Shop erfolgreich
zu sein.

Die Suchalgorithmen wurden entwickelt, um relevante, maßgebliche Seiten
anzuzeigen und den Benutzern ein effizientes Sucherlebnis zu bieten. Die
Optimierung Ihrer Website und Ihres Inhalts unter Berücksichtigung dieser
Faktoren kann dazu beitragen, dass Ihre Seiten in den Suchergebnissen
höher eingestuft werden.

=== Ist SEO wichtig für das Internet Marketing?

SEO ist ein grundlegender Bestandteil des digitalen Marketings, da Menschen
jedes Jahr Billionen von Suchanfragen durchführen, oft mit kommerzieller
Absicht, um Informationen über Produkte und Dienstleistungen zu finden.
Die Suche ist oft die primäre Quelle für digitalen Traffic für Marken und
ergänzt andere Marketingkanäle. Eine größere Sichtbarkeit und ein höheres
Ranking in den Suchergebnissen als Ihre Konkurrenz kann sich erheblich auf
Ihr Endergebnis auswirken.

Die Suchergebnisse haben sich jedoch in den letzten Jahren weiterentwickelt,
um den Benutzern direktere Antworten und Informationen zu geben, die die
Benutzer eher auf der Ergebnisseite halten, anstatt sie auf andere Websites
zu leiten.

Beachten Sie auch, dass Funktionen wie Rich Results und Knowledge Panels
in den Suchergebnissen die Sichtbarkeit erhöhen und Benutzern direkt in den
Ergebnissen mehr Informationen über Ihr Unternehmen liefern können.

Zusammenfassend ist SEO die Grundlage eines ganzheitlichen Ökosystems des
Marketings. Wenn Sie verstehen, was Ihre Website-Benutzer wollen, können
Sie dieses Wissen dann in Ihren Kampagnen (bezahlt und organisch), auf
Ihrer Website, in Ihren Social-Media-Eigenschaften und mehr implementieren.

=== Wie kann ich SEO lernen?

Für einen hilfreichen Einstieg in SEO stellt Ihnen unser Periodensystem der
SEO-Faktoren alle Schlüsselkonzepte vor, die Sie kennen müssen, einschließlich
der Elemente für erfolgreiches On-Page- und Off-Page-SEO sowie die „Toxine“
oder Taktiken, die schaden können Ihre Platzierungen.

.Accessing scheme for a static web
lightbox::kickstart-wiad--static-web-access[ 800, {data-kickstart-wiad--static-web-access} ]

callout::1["Web Browser"]
callout::2["Web Server"]
callout::3["Server-side rendered (prepared) static content", ml-2 mb-3]

Die Tabelle und der begleitende Bericht betrachten auch drei Nischen der Suche:

* Lokales SEO
* Verlags-/Nachrichten-SEO
* E-Commerce-SEO

Als Ergänzung zu unserem Periodensystem der SEO-Faktoren führt Sie der
SEO-Leitfaden von Search Engine Land durch die Grundlagen der Optimierung
für die Suche, damit Sie eine solide Strategie entwickeln können, um
organischen Traffic auf Ihre Website zu lenken.

/////
.Top Jamstack Generators
lightbox::kickstart-wiad--top-jamstack-generators[ 800, {data-kickstart-wiad--top-jamstack-generators} ]
/////


== SEO Leitfaden

Im folgenden Leitfaden erläutern wir diese Faktoren ausführlicher und heben
taktische Tipps von Experten für Suchmaschinenoptimierung hervor die Ihrer
Website helfen, mehr Besucher aus der *organischen* Suche zu gewinnen.

Kapitel 1 -- https://searchengineland-com/guide/seo/types-of-search-engine-ranking-factors/[Arten von Suchmaschinen-Erfolgsfaktoren, {browser-window--new}]::
// https://searchengineland-com/guide/seo/types-of-search-engine-ranking-factors
Dies sind die On- und Off-Page-Faktoren, die Ihre Suchrankings beeinflussen
können. Wir werden uns auch Nischenbranchen in SEO und toxische SEO-Taktiken
ansehen, die es zu vermeiden gilt.

Kapitel 2 -- https://searchengineland-com/guide/seo/content-search-engine-ranking[Erfolgsfaktoren für Inhalte und Suchmaschinen, {browser-window--new}]::
// https://searchengineland-com/guide/seo/content-search-engine-ranking
Behalten Sie diese Elemente im Hinterkopf, um qualitativ hochwertige
Inhalte zu erstellen, die Suchmaschinen und Ihre Zielgruppen lieben werden.

Kapitel 3 -- https://searchengineland-com/guide/seo/site-architecture-search-engine-ranking[Site-Architektur und Erfolgsfaktoren von Suchmaschinen, {browser-window--new}]::
// https://searchengineland-com/guide/seo/site-architecture-search-engine-ranking
Gehen wir hinter die Kulissen und schauen uns die Aspekte Ihrer Site an,
die es Suchmaschinen erleichtern, auf die Benutzererfahrung zuzugreifen und
sie zu beeinflussen.

Kapitel 4 -- ttps://searchengineland-com/guide/seo/html-code-search-engine-ranking[Erfolgsfaktoren für HTML-Code und Suchmaschinen, {browser-window--new}]::
// https://searchengineland-com/guide/seo/html-code-search-engine-ranking
HTML-Tags und strukturierte Daten helfen dabei, Informationen auf Ihrer
Website zu organisieren und Suchmaschinen dabei zu helfen, Ihre Inhalte
zu verstehen.

Kapitel 5 -- https://searchengineland-com/guide/seo/trust-authority-search-rankings[Vertrauen, Autorität, Expertise und Suchrankings, {browser-window--new}]::
// https://searchengineland-com/guide/seo/trust-authority-search-rankings
Wie Ihre Benutzer mit Ihrer Website interagieren, sowie ihr Ruf und ihre
Autorität, hilft Suchmaschinen zu bestimmen, ob sie es wert ist, Benutzern
angezeigt zu werden.

Kapitel 6 -- https://searchengineland-com/guide/seo/link-building-ranking-search-engines[Linkbuilding & Ranking in Suchmaschinen, {browser-window--new}]::
// https://searchengineland-com/guide/seo/link-building-ranking-search-engines
Warum Links immer noch wichtig sind und was sie Suchmaschinen über Ihre
Inhalte verraten.

Kapitel 7 -- https://searchengineland-com/guide/seo/personalization-search-engine-rankings[Personalisierung und Suchmaschinen-Rankings, {browser-window--new}]::
// https://searchengineland-com/guide/seo/personalization-search-engine-rankings
Dies sind die benutzerspezifischen Elemente wie Standort und Absicht, die
sich auf die Ergebnisse auswirken können, die Benutzer sehen.

Kapitel 8 -- https://searchengineland-com/guide/seo/violations-search-engine-spam-penalties[Toxine und Suchmaschinen-Spamstrafen, {browser-window--new}]::
// https://searchengineland-com/guide/seo/violations-search-engine-spam-penalties
Vorsicht vor SEO-„Abkürzungen“. Wenn Sie mit diesen Taktiken erwischt werden,
kann dies möglicherweise zu einer Strafe für manuelle Maßnahmen führen oder
sogar dazu führen, dass Ihre Website aus dem Suchindex gestrichen wird.

Kapitel 9 -- https://searchengineland-com/guide/seo/emerging-verticals-in-search[Aufstrebende Branchen in der Suche, {browser-window--new}]::
// https://searchengineland-com/guide/seo/emerging-verticals-in-search
Sprach-, lokale, Bild- und Videosuche stellen neue Möglichkeiten für
Benutzer dar, das zu finden, wonach sie suchen. Während sie jeweils
nuancierte Möglichkeiten für Marken bieten, basieren sie dennoch auf den
Grundprinzipien von SEO.


== Search Engine SEO Library

In addition to covering SEO generally, Search Engine Land also has search
engine optimization areas specifically for the major search engines:

* https://searchengineland.com/library/google/google-seo/[Google SEO, {browser-window--new}]
* https://searchengineland.com/library/google/google-algorithm-updates/[Google Algorithm Updates, {browser-window--new}]
* https://searchengineland.com/guide/google-search-console/[Google Search Console, {browser-window--new}]
* https://searchengineland.com/guide/bing/[Bing SEO, {browser-window--new}]
