== The Themes Menu

Themes adjust the website's appearance based on the core CSS rules and
definitions of Bootstrap. Themes do not change the framework's functionality
but modify rule-based, e.g., the color scheme, fonts, sizes, or the
appearance of more complex elements like forms or tables. Additionally, a
theme may add additional components to extend the Bootstrap's framework.

Modifying the CSS styles of link:{url-bs--home}[Bootstrap, {browser-window--new}]
is not rocket science. But, to be honest, some knowledge is needed for
link:{url-w3org--css-spec}[the CSS technology, {browser-window--new}] to do so.
We encourage you to spend some time first on learning CSS. To learn what is the
link:{url-w3schools--css-tutorial}[design base, {browser-window--new}] of each
and every website.

.Themes menu
lightbox::images--themes-menu[ 1280, {data-images--themes-menu} ]

Thanks to the people at link:{url-bootswatch--home}[Bootswatch, {browser-window--new}],
a great set of already prepared Bootstrap stylesheets in various designs are
available on their website. There is no need to start from scratch. It is not
needed to re-define all the Bootstrap variables, and rebuild the framework
files to create a new theme. Many different styles are available. What is
already available at Bootswatch is at least a good base for your modifications;
your unique design.

Besides the bunch of different stylesheets at Bootswatch, an
link:{url-bootswatch--api}[Integration API, {browser-window--new}] is provided
that helps a lot to integrate available designs into an existing site. This API
is the base to integrate selectable Bootswatch stylesheets into the J1 Theme
navigation system for easy use.

=== Apply a theme

The base for designing pages using the J1 Theme is the theme Uno, a modern
light theme used for many types of websites. And what we mentioned
already, web design is not: one size fits all. The theme Uno can be seen as
a good base, a starting point. Combining Uno and a different theme may be a fast
solution for your site!?

You can find all available themes and stylesheets on your pages
from the menu Themes. You're invited to check how a page is changing for
its design if other stylesheets, other ideas of web design are used.

TIP: Changing BS-based styles is one thing. Changing from one theme to the
next at runtime is a bit more challenging. For the first version of the J1
Template, many styles are automatically changed for J1 specific components,
but not all of them for now.

Select a theme from this menu, and a new BS-based stylesheet is automatically
applied to your pages.
