---
title:                                  Themes
tagline:                                Bootstrap Styles
date:                                   2020-11-10 00:00:00
description: >
                                        J1 Theme offers various unique functionalities compared to other Jekyll
                                        themes and templates. Bootstrap themes for the J1 Theme are based on the
                                        free and open-source CSS front-end framework Bootstrap of version V5. The
                                        Bootstrap themes for the J1 enable the presentation of different versions
                                        (skins) of the same site using already prepared Bootstrap CSS templates.
keywords: >
                                        Jekyll, Theme, JekyllOne, CSS, Bootstrap, Style, Skin, Roundtrip

categories:                             [ Roundtrip ]
tags:                                   [ Bootstrap, Module, Theme ]

image:
  path:                                 /assets/images/modules/attics//themes-1920x1280-bw.jpg
  width:                                1920
  height:                               1280

regenerate:                             false
permalink:                              /pages/public/learn/roundtrip/themes/

resources:                              [ animate, rouge, clipboard, lightbox ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/images/modules/attics//themes-1920x1280-bw.jpg
          alt:                          Photo by Clem Onojeghuo on Unsplash
          badge:
            type:                       unsplash
            author:                     Clem Onojeghuo
            href:                       https://unsplash.com/@clemono
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Bootstrap themes (styles) for the J1 are based on the free and open-source
CSS front-end framework of version V5. The Bootstrap theme feature enables
the presentation of different versions of the same site using already prepared
Bootstrap CSS styles.

link:{url-bs--home}[Bootstrap, {browser-window--new}] is an HTML, CSS and
Javascripts Library that focuses on simplifying the development of modern web
pages. The primary purpose of applying the framework to J1 is to provide a
general standard for colors, sizes, fonts, and the overall layout of a
J1-based site.

Using Bootstrap themes results in a uniform appearance for the content in
terms of the overall layout, text, tables, and form elements across all
modern web browsers available on the market. In addition, developers can
take advantage of CSS classes defined in Bootstrap to customize content
individually.

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
include::{documentdir}/themes_bootstrap.asciidoc[]

== What next

J1 Template is an excellent base for documentation websites. J1 supports
powerful code highlighting to distinguish different source code elements
visually. Highlighting makes the code more readable and easier to understand
by applying different colors or styles to different parts of the code.

Different programming languages have specific syntax rules and conventions,
so code highlighting is tailored to each language. For example, in a typical
JavaScript syntax highlighting scheme, keywords like `if`, `for`, and
`function` may be displayed in one color, while variables and strings are
displayed in another.

The highlighter _Rouge_ is a native Ruby themeable syntax highlighter fully
integrated width J1 Template. The highlighter supports 100+ different languages
and generates HTML output using standard ANSI 256 colors displayed by all
current browsers.

To check the code highlighter J1 Theme offers, go for the
link:{url-roundtrip--rouge-hightlighter}[Rouge Code Highlighter].
