---
title:                                  Present Images
tagline:                                Manage Image Contents
date:                                   2020-11-03 00:00:00
description: >
                                        J1 Theme support valuable features to manage your image-based
                                        content using lightboxes, carousels, sliders, and galleries.
                                        The image modules of J1 Theme offer a wide range of complex
                                        functionality based on powerful OpenSource libraries like
                                        Lightbox2, Master Slider, LightGallery, or JustifiedGallery
                                        for high-end, masonry-styled preview maps.
keywords: >
                                        Jekyll, Theme, JekyllOne, Images, Lightboxes, Carousels, Sliders,
                                        Galleries, Lightbox2, Master Slider, LightGallery, JustifiedGallery,
                                        Roundtrip

categories:                             [ Roundtrip ]
tags:                                   [ Module, Carousel, Lightbox, Image, Slider ]

image:
  path:                                 /assets/images/modules/attics/1920x1280/quino-al-2.jpg
  width:                                1920
  height:                               1280
  alt:                                  Photo by Quino Al Angel on Unsplash

permalink:                              /pages/public/learn/roundtrip/present_images/
regenerate:                             false

resources:                              [
                                          animate, clipboard, carousel,
                                          justifiedGallery, lightbox, lightGallery,
                                          masterslider, rouge
                                        ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/quino-al-2.jpg
          alt:                          Photo by Quino Al Angel on Unsplash
          badge:
            type:                       unsplash
            author:                     Quino Al Angel
            href:                       https://unsplash.com/@quinoal
---


// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:url-lightbox2--home:                   https://lokeshdhakar.com/projects/lightbox2/
:url-lightbox2--github:                 https://github.com/lokesh/lightbox2/

:url-justified-gallery--home:           https://miromannino.github.io/Justified-Gallery/
:url-justified-gallery--github:         https://github.com/miromannino/Justified-Gallery/

:url-j1-docs--carousel-module:          https://jekyll.one/pages/public/manuals/modules/carousel/
:url-j1-docs--lightbox-module:          https://jekyll.one/pages/public/manuals/modules/lightbox/
:url-j1-docs--masterslider-module:      https://jekyll.one/pages/public/manuals/modules/masterslider/

:url-j1-masterslider-slider-previewer:  https://jekyll.one/pages/public/previewer/masterslider/


//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Welcome to the preview page focussing on the image module. This page shows
all the valuable features of the J1 Theme to manage your image-based content
using using lightboxes, carousels, sliders, and galleries. The image modules
of J1 Theme offer a wide range of complex functionality based on powerful
OpenSource libraries like Lightbox2, Master Slider, LightGallery, or
JustifiedGallery for high-end, masonry-styled preview maps.

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
// [role="notranslate"]
[role="mt-4"]
== J1 Lightbox blocks

A Lightbox is, in general, a helper which displays enlarged, almost
screen-filling versions of images (or videos) while dimming the remainder
of the page. The technique, introduced by Lightbox2, gained widespread
popularity thanks to its simple style. The term lightbox has been employed
since then for Javascript libraries to support such functionality.

For the J1 Theme, two different lightboxes are available:

* Lightbox2 (lightbox)
* LightGallery

The default tool employed by J1 Theme is Lightbox2, a Javascript library
written by _Lokesh Dhakar_. The name of that (build-in) is *lightbox*.
For more complex use cases, like a thumbnail gallery preview or video support,
LightGallery can be used alternatively.

NOTE: The name LightGallery implies a sort of a Gallery, but the library is a
_lightbox_. And, LightGallery provides much more functionality on image-based
data rather than enlarged displaying of images. See the examples below to check
for the differences in comparison to the simpler Lightbox2 lightbox.

Both lightboxes are fully integrated to be used as standalone modules or
used as helpers *under-the-hood* by other apps or modules focussing on
image-data like gallery or carousel, the build-in carousel module.

TIP: For details of the default lightbox of J1 Theme, see the documentation
under the link:{url-j1-docs--lightbox-module}[Lightbox module, {browser-window--new}].


== Lightbox block examples

Find below an example of using the lightbox Lightbox standalone. See how
single (individual) images are linked for use with Lightbox.

.Lightbox block for standalone images
lightbox::example-standalone[ 800, {data-images-standalone}, role="mb-4" ]

Lightbox supports image groups (image sets). Click on the images below to
see how Lightbox manages a group of images.

.Lightbox block for grouped images
lightbox::example-group[ 395, {data-images-group}, group, role="mb-4 wm-800" ]

=== LightGallery example

LightGallery provides more complex functions on image data. The module
supports a gallery-style thumbnail preview plus image resizing, a download
dialog, sharing provider support, and more helpful. Check what
LightGallery can do this by the following example.

gallery::jg_old_times[ role="mb-4 wm-800" ]

== J1 Carousel App

J1 Carousel is based on OWL Carousel V1 in the latest (and unfortunately
last) version of 1.3.3. OWL Carousel is a clean and neat _jQuery_ slider
plugin for creating fully responsive and touch-enabled carousel sliders.

////
NOTE: OWL Carousel V1 is no longer available on the Internet; for an
unknown reason. Anyway, the J1 Theme is using this version of OWL
Carousel is a build-in carousel module because the software does an excellent
job, is based on an MIT license with no issues using them for private and
business use. And offers a lot of great features!
////

=== Simple Text Carousel

A slider or carousel is typically used for displaying images. Still, the
implementation for the J1 Theme supports a lot more sources to be
displayed as a slide show: simple text, for example.

.Carousel example
carousel::demo_text_carousel[role="mb-3"]

Important statements or topics can be placed, e.g., on top of an article or
a paragraph, to give them better visibility. In one line, you can present
many facts to know animated for the reader's attention within a single
line. No much space is needed!

=== Parallax Text Carousel

A more eye-minded type of text-based slide show is a parallax text slider. If
you want to emphasize your statements focussing the meaning, this kind of a
slide show may be interesting. Image-based slide shows may draw off the
reader's attention from the text, therefore a pure text-based presentation
maybe the better choice.

.Carousel example
carousel::demo_text_carousel_parallax[role="mb-3"]

Parallax text shows can be placed as banners on a page. For text shows,
different animations are available. Internally, J1 Theme uses some of
the great CSS styles offered by _animate.css_.

TIP: Have a look a https://daneden.github.io/animate.css/[Dan Eden's home page, {browser-window--new}]
to see all the possible dynamic styles you can create based on pure CSS.
Some of them are implemented for the J1 Carousel for animation. See the
documentation for the
link:{url-j1-docs--carousel-module}[Carousel module, {browser-window--new}]
for more details.

=== Simple Image Carousel

Carousels are mostly used for pictures data to animate the images as a series.
Find with the following some examples of how to use a carousel for your image
data.

A simple image show is useful, for example, as an animated (or not animated)
banner presenting exciting things about your site or the products offered.

.Carousel example
carousel::demo_simple[role="mb-3"]

=== Carousel + Caption + Lightbox

Carousels are used for an exceptionally compact form of image galleries.
This example shows some pictures having individual caption text and supports
a lightbox to enlarge images full size. For the example below, an almost simple
lightbox is used: Lightbox2; or short: lightbox.

.Carousel example
carousel::demo_cats[role="mb-3"]

The J1 module lightbox is a simple Lightbox but offers a bunch of impressive
features for displaying images. For example, the lightbox can display all
images (of a carousel) as a group. If one picture is opened in the lightbox,
others are browsed by easy-to-use control buttons.

=== One Slide Carousel + Lightbox

The build-in Carousel carousel supports multiple and single image shows.
Here you find an example of a single image slide show with controls enabled
to browse all images back and forth. An indicator below the slider shows how
many images the show contains.

.Carousel example
carousel::demo_oneslide[role="mb-3"]

== J1 Master Slider

The Javascript tool _Master Slider_ is a 3rd party plugin fully integrated
into the J1 Theme by the module `masterslider`. J1 Theme uses the
*free* version of Master Slider (MS Lite). The Lite version does *not* support
all features: the functionality of  *filters*, *layouts* are limited and no
*overlay* techniques are supported by the MS Lite version.

// WARNING: The Master Slider (MS Lite and Pro version) is a so-called _jQuery_
// Plugin. _jQuery_ can simplify Javascript code a lot but will slow-down
// the runtime performance of the JS code. Expect for slower browsers and
// platforms, like mobiles or tablets, initializing an MS Slider will take
// a while to be finished.

=== Carousels versus Sliders

Sliders and Carousels are focussing quite the same thing: presenting image data
dynamically as an app. The features of Sliders go far beyond what simple
Carousels can do: presenting image-based data as *slideshows*. Well-known
Office Products to create *presentations* are _Microsoft Powerpoint_ or
_Google Docs_. Modern sliders like _Master Slider_ provide similar features to
present animated *shows* (presentations) based on digital image data combined
with text elements, buttons, or overlay techniques, e.g., for images or
other digital data sources.

In short: Carousels are used to present images, and sliders are used to create
complex image-based slideshows (presentations).

TIP: For more details of the dimplementation of Master Slider of J1 Theme, see
find  documentation at
link:{url-j1-docs--masterslider-module}[Master Slider module, {browser-window--new}].

=== MS Slider using Controls + Filters + Lightbox

The following slider uses the (CSS) filter feature of Master Slider.
Filters can be used, for example, to *transform* the *style* of the images
presented by a slider. In this example, the slider images are transformed
from style *color* to *sepia*.

WARNING: Lightbox support is only available for the MS Lite version of J1
Theme. The product versions *MS Lite* and *MS Pro* does not support
Lightboxes on sliders out-of-the-box.

TIP: Click on the Lightbox symbol mdi:image-outline[18px, md-gray] in the
slides to see the *colored* images configured for the slider.

masterslider::ms_00001[role="mt-4 mb-5"]

=== MS Slider using Text Elements

One of the major features of sliders is to present additional (animated)
elements, like text data, connected to the images presented by a slider:
the slideshow. MS Slider provides functions to combine images and text
elements: the *MSInfo* element.

masterslider::ms_00003[role="mt-4 mb-5"]

=== MS Slider using ThumbImages

To give the users better control over a slideshow, sliders provide complex UI
elements like *thumbs* placed side-by-side (left|right), at the top, or at
the bottom of a slideshow. Find two examples to control a slideshow by
*thumb images*.

masterslider::ms_00004[role="mt-4 mb-5"]

masterslider::ms_00005[role="mt-4 mb-5"]

=== MS Slider using MS Info in a complex Layout

The following slider presents a slideshow that combines an MSInfo element
at the bottom and the MS Layout `partialview`. A slideshow typically presents
a larger number of slides. The layout `partialview` accompanies the *active*
slide by their neighbors on the left and the right.

masterslider::ms_00009[role="mt-4"]

=== More about Master Sliders

If you're interested to learn more about MS Sliders, go for the following
documents:

* link:{url-j1-masterslider-slider-previewer}[MS Slider Previewer, {browser-window--new}]
* link:{url-j1-docs--masterslider-module}[MS Slider module documentation, {browser-window--new}]


== JustifiedGallery

link:{url-justified-gallery--home}[JustifiedGallery, {browser-window--new}]
is a great _jQuery_ Plugin to create responsive, infinite, and high-quality
justified image galleries. J1 Theme combines the Gallery with the lightboxes
supported to enlarge the images of a gallery. See the gallery in action; and
for sure, all that you see is even responsive. Change the size of your current
browser window, by width or height to see what will happen!

Pictures you've made are typically not even in size. Images may have the
same size (resolution), but some are orientated landscapes, or others
may be portraits. For that reason, a more powerful gallery is needed to create
so-called justified views. JustifiedGallery uses a so-called masonry grid
layout. It works by placing elements in an optimal position based on available
horizontal and vertical space. Sort of like mason fitting stones in a wall.
You'll have seen it in use all over the Internet!

.JustifiedGallery example
gallery::jg_customizer[role="mb-4"]

== What next

Hopefully, you've enjoyed exploring the possibilities J1 offers for managing
and displaying digital image content. But much, much more can the J1 do for
your web.

Incredible? See the next example page link:{url-roundtrip--present-videos}[Present Videos].
