---
title:                                  J1
tagline:                                about
date:                                   2021-01-01 00:00:00 +100
description: >
                                        Things you should know about this site,
                                        the people and the software and/or
                                        services provided.

categories:                             [ About ]
tags:                                   [ Software, Platforms, Contributers ]

scrollbar:                              false
regenerate:                             false

permalink:                              /pages/public/about/site/

resources:                              [ animate ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/modules/attics/runner-1920x1200.jpg
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

// Attribute settings for section control
//
:badges-enabled:                        true
:language-en:                           true

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ifeval::[{badges-enabled} == true]
{badge-j1--license} {badge-j1--version-latest} {badge-j1-gh--last-commit} {badge-j1--downloads}
endif::[]

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
ifeval::[{language-en} == true]
== About this site

Whether you work solo or as part of a team, it’s always a great idea to
help visitors put a face to the names behind a website. The best place to
include a bit of information about you and your team is on your homepage with
an *About* page so that no one will miss it.

Good luck presenting your site to the world!
endif::[]

ifeval::[{language-de} == true]
== Über diese Site

Egal ob Sie alleine oder im Team arbeiten, es ist immer eine gute Idee
Besuchern helfen, den oder die Namen hinter einer Website ein Gesicht zu
geben. Der beste Ort um ein paar Informationen über dich und dein Team zu
geben, ist auf deiner Homepage mit Hilfe eine *About*-Seite. Dann gehen
die wichtigen Infos nicht verloren.

Viel Glück beim Präsentieren Ihrer Site!
endif::[]
