---
title:                                  J1 Template
tagline:                                features
date:                                   2021-09-29 00:00:00
description: >
                                        Things you should know about this site,
                                        about the software used. Read a bit what
                                        people, what companies has contributed
                                        to make a project like J1 Template real.

keywords: >
                                        overview, software, platforms, contributers, features,
                                        general, modules and extensions, addons and integrations,
                                        opensource, free, load, download, start, starter, example,
                                        high, easy, use, secure, encrypt, standard, popular,
                                        generate, develop, create, learn, distribute, publish, deploy,
                                        beginner, advanced, expert, student, learner, writer, reader, visitor
                                        framework, toolkit, integration, extension, module, api,
                                        dynamic, static, generator, client, server, internet, local, localhost
                                        page, web, website, webdesign, material, design, responsive,
                                        javascript, nodejs, ruby, windows, linux, osx, mac, os,
                                        http, https, html, html5, css, scss, style,
                                        browser, firefox, chrome, edge, opera, safari,
                                        configuration, generator, navigation, menu, dropdown, fab, action, button
                                        application, interface, provider, api, repository,
                                        cookie, language, translation, gdpr, dsgvo, privacy,
                                        asciidoc, aciidoctor, bootstrap, jekyll, liquid,
                                        hyvor, disqus, git, github, netlify, heroku, apple, microsoft,
                                        provider, service, internet, support,
                                        google, analytics, advertising, search, console, silverlight, score,
                                        j1, template, jekyllone, comment

tags:                                   [ Overview ]
categories:                             [ Software, Platforms, Contributers ]

scrollbar:                              false
comments:                               false

permalink:                              /pages/public/about/features/
regenerate:                             false

resources:                              [ animate, lightbox ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/modules/attics/runner-1920x1200.jpg
          alt:                          Runner

#        - url:                          /assets/images/modules/attics/ryan-quintal-1920x1280.jpg
#          alt:                          Photo by Ryan Quintal on Unsplash
#          badge:
#            type:                       unsplash
#            author:                     Ryan Quintal
#            href:                       https://unsplash.com/@ryanquintal
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:badges-enabled:                        true

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ifeval::[{badges-enabled} == true]
{badge-j1--license} {badge-j1--version-latest} {badge-j1-gh--last-commit} {badge-j1--downloads}
endif::[]

// Include sub-documents
// -----------------------------------------------------------------------------
== Features

J1 Template is a *gem-based* website template to be used with the static site
generator _Jekyll_. The Template System cannot operate on its own. A Ruby
development environment is needed to run J1. The easiest way to learn how J1
works to create a website is the tutorial
{url-j1-web-in-a-day--meet-and-greet}[Web in a Day, {browser-window--new}].

If you're an experienced user of _Jekyll_, the latest version is available at
{url-j1--download}[RubyGems, {browser-window--new}].

=== General

* Jekyll 4.2 support
* Ruby 2.7 support
* Asciidoc (Asciidoctor) and Markdown support
* Asciidoctor plugins included
* Bootstrap V5 (v5.1.3)
* Responsive Design
* Material Design
* Responsive Text
* Responsive HTML tables
* Compressed HTML, CSS and Javascript support
* Themes support (Bootswatch)
* Icon Font support (MDI, FA, Iconify, Twitter Emoji)
* Themeable source code highlighting (Rouge)
* Desktop and Mobile navigation ready
* Fully configurable
* Highest Google Lighthouse scores

=== Modules and Extensions

* Bootstrap V5 extensions included
* Asciidoctor extensions|plugins included
* Smooth-Scroll support on all pages
* Full-text search engine included (Lunr)
* Blog Post navigation included
* Cookie Consent module included (includes GDPR compatible OptIn/OptOut support)
* Translator module included (includes GDPR compatible OptIn/OptOut support)
* Advertising module included (includes GDPR compatible OptIn/OptOut support)
* Analytics module included (includes GDPR compatible OptIn/OptOut support)
* Clipboard module included
* Floating Action Buttons|Menus included
* Navigation module (multi purpose) included
* Lightbox modules included
* Gallery modules included
* Carousel module included
* Video modules included (HTML5 Video, YouTube, Vimeo)

=== Addons and Integrations

* Featured example content included
* Royalty free images included
* Support of comment provider APIs (Disqus, Hyvor)
* Google Analytics support (includes GDPR compatible OptIn/OptOut support)
* Google Addsense support (includes GDPR compatible OptIn/OptOut support)
* Google Translate support (includes GDPR compatible OptIn/OptOut support)
* Deploy on Github Pages (source only), Netlify and Heroku ready

=== Supported platforms

J1 is supported on all current x64-based OS:

* Windows 10|11
* Windows WSL 2
* Linux, kernel version >= 4.15 (e.g. Ubuntu  18.x LTS)
* OSX, version >= 10.10.5 (Yosemite)

NOTE: *32-bit* versions (x32) are generally NOT supported for *all* platforms.
