---
title:                                  Starter
tagline:                                Learn The Features

date:                                   2022-12-31
#last_modified:                         2023-01-01

description: >
                                        J1 Template is a Bootstrap V5 website template for the static
                                        site generator Jekyll. The Theme is free to use and
                                        can be downloaded at RubyGems as a Ruby Gem. The
                                        Theme supports a wide range of websites, from a personal
                                        website, a blog web, a documentation site to classic
                                        company webs.

keywords: >
                                        Jekyll, Theme, JekyllOne, J1, Theme, Features

categories:                             [ About ]
tags:                                   [ J1, Features ]

image:
  path:                                 /assets/images/modules/attics/1920x1280/j1-starter-mockup-1.jpg
  width:                                1920
  height:                               1280

regenerate:                             false
permalink:                              /pages/public/about/features/

resources:                              [ animate, lightbox ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/j1-starter-mockup-1.jpg
          alt:                          J1 Starter Mockup
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:badges-enabled:                        false

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}

ifeval::[{badges-enabled} == true]
[role="mb-5"]
{badge-j1--version-latest} {badge-j1--downloads}
endif::[]

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
J1 Template is a Bootstrap V5 website template for the static site generator Jekyll.
The Theme is free to use and can be downloaded at
link:{url-j1--download}[RubyGems, {browser-window--new}] as a Ruby Gem.
The Theme supports a wide range of websites, from a personal website,
a blog web, a documentation site to classic company webs.

Read what people and companies have contributed to making a project like J1
Theme real.

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== General Features

* _Windows_, _Linux_ and _MacOS_ platforms supported
* _Jekyll_ v4 Support
* _Ruby_ v3 Support
* Asciidoc and Markdown Support
* _Asciidoctor_ plugins included
* _Bootstrap_ V5 Support
* Responsive Design
* Responsive Text
* Responsive HTML Tables
* Compressed HTML, CSS and Javascript Support
* Themes from _Bootswatch_ supported (Bootstrap V5)
* Icon Font Support for _MDI_, _FA_, and _Iconify_
* Themeable source code highlighting (_Rouge_)
* SEO Support
* Auto-Optimization for CSS-, JS, and HTML files
* Desktop and Mobile navigation ready
* Fully configurable, no programming needed
* Near 100/100/100 _Google Lighthouse_ Scores

[role="mt-5"]
== Modules and Extensions

* _Bootstrap_ extensions included
* _Asciidoctor_ extensions included
* Screen Reader (TTS) support
* Infinite Scoll Support
* Animate on Scroll Support
* Lazy Load Support for CSS- and Font Icon files
* Support for configurable HTML Selects (msDropdown, slimSelect)
* Full-text Search Engine (Lunr) included
* Master Header Module included
* Cookie Consent Module (GDPR/CPRA compatible OptIn/Out) included
* Clipboard Module included
* Floating Action Menu Buttons (FAMs) included
* Navigation Modules included (Desktop and Mobile)
* Blog Post Navigation included
* Blind Text Support (Lorem ipsum)
* iFrame Support
* Masonry Support
* Lightbox Modules included
* Gallery Modules included
* Carousel Modules included
* Slider Modules included
* Video Player Modules included

[role="mt-5 mb-7"]
== Addons and Integrations

* *Starter Web* including featured example content
* *Royalty free* Images included
* Comment Provider Support (_Disqus_ and _Hyvor_)
* _Google Adsense_ Support
* _Google Analytics_ Support (includes OptIn/OptOut support)
* _Google Translation_ Support
* Deploy on _Github Pages_, _Netlify_ and _Heroku_ ready
