---
title:                                  Starter
tagline:                                Report on Failures

date:                                   2022-01-01
#last_modified:                         2023-01-01

description: >
                                        J1 Template is a Bootstrap V5 website template for the static
                                        site generator Jekyll. Please report failures.
                                        Although I endeavor to keep this
                                        site as up-to-date as possible, even the best sites will
                                        have some bugs. If you spot any typos, factually
                                        outdated or incorrect information, formatting errors, or
                                        similar problems, please report issues so I can correct them.
keywords: >
                                        Jekyll, Theme, JekyllOne, J1, Project, Software, Service

categories:                             [ About ]
tags:                                   [ Issues ]

image:
  path:                                 /assets/images/modules/attics/1920x1280/j1-starter-mockup-1.jpg
  width:                                1920
  height:                               1280

fab_menu_id:                            default
regenerate:                             false
permalink:                              /pages/public/about/reporting_issues/

resources:                              [ animate ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/j1-starter-mockup-1.jpg
          alt:                          J1 Starter Mockup
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

// Attribute settings for section control
//
:badges-enabled:                        false

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}

ifeval::[{badges-enabled} == true]
[role="mb-5"]
{badge-j1--version-latest} {badge-j1--downloads}
endif::[]


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Please report failures. Although I endeavor to keep this site as up-to-date
as possible, even the best sites will have some bugs. If you spot any typos,
factually outdated or incorrect information, formatting errors, or similar
problems, please report issues so I can correct them.

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
The source pages for the J1 Template Starter are maintained in a _GitHub_
repository. _GitHub_ provides both an issue tracker and a history of changes.
To report problems with the content and display, simply open a new issue and
describe the problem and what page(s) it occurs on.

[IMPORTANT]
====
A link:{url-github--join}[free account, {browser-window--new}]
at GitHub_ is required in order to open new issues.
====

To report issues, please go on _Github_ for the repo
link:{url-j1--reporting-issues}[J1 Starter Theme, {browser-window--new}].
