---
title:                                  Jekyll One
tagline:                                About This Site
date:                                   2022-01-01 00:00:00
description: >
                                        Things you should know about this site, the people, the software
                                        and the services provided by this project.
keywords: >
                                        Jekyll, Theme, JekyllOne, J1, About, Project, Site

categories:                             [ About ]
tags:                                   [ Site, Review ]

image:
  path:                                 /assets/images/modules/attics/1920x1280/j1-theme-mockup-1.jpg
  width:                                1920
  height:                               1280
  alt:                                  J1 Theme Mockup

fab_menu_id:                            page_ctrl
scrollbar:                              false
comments:                               false

regenerate:                             false
permalink:                              /pages/public/about/site/

resources:                              [ animate ]
resource_options:
  - attic:
      padding_top:                      600
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/j1-theme-mockup-1.jpg
          alt:                          J1 Themes Mockup
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

// Attribute settings for section control
//
:badges-enabled:                        true

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}

ifeval::[{badges-enabled} == true]
[role="mb-4"]
{badge-j1--version-latest} {badge-j1--downloads}
endif::[]


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Things you should know about this site, the people, the software and the
services provided by this project.

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
== About this site

Whether you work solo or as part of a team, it’s always a great idea to
help visitors put a face to the names behind a website. The best place to
include a bit of information about you and your team is on your homepage with
an About page so that no one will miss it.

Good luck presenting your site, your project to the world!
