---
title:                                  Asciidoctor PDF Themes
tagline:                                Theming Guide

date:                                   2022-01-01
#last_modified:                         2023-01-01

description: >
                                        J1 Template is a Bootstrap V5 website template for the static
                                        site generator Jekyll.
                                        Asciidoctor PDF is a native PDF converter for AsciiDoc that plugs
                                        into the pdf backend. It bypasses the requirement to generate an
                                        intermediary format such as DocBook, Apache FO, or LaTeX. Instead,
                                        you can use Asciidoctor PDF to convert your documents directly
                                        from AsciiDoc to PDF. The aim of this library is to take the pain
                                        out of creating PDF documents from AsciiDoc.

categories:                             [ Knowledge ]
tags:                                   [ Asciidoctor, PDF, Converter ]

image:
  path:                                 /assets/images/modules/attics/sigmund-1920x1280.jpg
  width:                                1920
  height:                               1280

exclude_from_search:                    true
permalink:                              /pages/public/skeleton/documentation/200_themes/
regenerate:                             false

resources:                              [ animate, lightbox, rouge ]
resource_options:
  - attic:
      alignY:                             0.3
      slides:
        - url:                          /assets/images/modules/attics/sigmund-1920x1280.jpg
          alt:                          Photo by Sigmund on Unsplash
          badge:
            type:                       unsplash
            author:                     Sigmund
            href:                       //unsplash.com/@sigmund
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set page (local) attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
The theming system in *Asciidoctor PDF* is used to control the layout and styling
of the PDF file *Asciidoctor PDF* generates from AsciiDoc. This document describes
how the theming system works, how to define a custom theme in YAML and how to
activate the theme when running *Asciidoctor PDF*.

[IMPORTANT]
====
If you're using a custom theme, you're expected to bring your own
fonts or declare the fonts from the default theme. If you don't declare your
own fonts, the built-in PDF (afm) fonts will be used, which only support
WINANSI characters (similar to Basic Latin).
====

// Include documents
// -------------------------------------------------------------------
include::{documentdir}/200_themes.asciidoc[]
