---
title:                                  Romance
title_extention:                        Collections are Jekyll's most powerful feature
tagline:                                Romance Literature

date:                                   2023-01-29
#last_modified:                         2023-01-01

description: >
                                        Romance Literature in the Book Shelf
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap,
                                        collections

categories:                             [ Books ]
tags:                                   [ Romance, Preview ]

image:
  path:                                 /assets/image/module/attic/giammarco-boscaro-1920x1280.jpg
  width:                                1920
  height:                               1280

robots:
  index:                                true
  follow:                               true

toc:                                    false
fab_menu_id:                            default
regenerate:                             false
permalink:                              /pages/public/learn/bookshelf/article_previewer/romance/

resources:                              [ masonry ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/image/module/attic/giammarco-boscaro-1920x1280.jpg
          alt:                          Photo by Giammarco on Unsplash
          badge:
            type:                       unsplash
            author:                     Giammarco
            href:                       //unsplash.com/@giamboscaro
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

{% comment %} Liquid procedures
-------------------------------------------------------------------------------- {% endcomment %}
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}
{% capture create_collection_article_preview %}themes/{{site.template.name}}/procedures/collections/create_collection_article_preview.proc{% endcapture %}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="none" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
The romance genre is a popular category of books that consistently churns out
bestsellers. The aim of the genre is simple, showcasing a love story where
two people overcome adversity to obtain their happily ever after. According to
the Romance Writers of America, women count for 82% percent of the genre’s
readership.

[NOTE]
====
*Resize* the browser window to see the `masonry` module, applied on
this page, in action. All elements gets automatically *re-ordered* to fit
the grid positions calculated by the module.
====

mdi:clock-time-five-outline[24px, md-gray mr-2]
*5 Minutes* to read

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== Available Books

Find below all available articles in the `romance` collection. The content is
automatically generated and taken from the articles this collection
contains.

.Collection Romance
masonry::collection_romance[role="mb-7"]

////
++++
<div class="row mb-4">
  <div class="col-md-12 col-xs-12">
    {% include {{create_collection_article_preview}} collection=site.romance %}
  </div>
</div>
++++
////
