---
title:                                  J1 Template
tagline:                                Cheatsheet for daily use

date:                                   2023-05-19
#last_modified:                         2023-01-01

description: >
                                        J1 Template is a Bootstrap V5 website template for the static
                                        site generator Jekyll.
                                        The Cheatsheet discuss j1 commands for daily use.
                                        The Template system J1 is a creation tool used to build
                                        simple but fully configurable modern static websites
                                        using the generator Jekyll.
keywords: >
                                        Jekyll, Theme, JekyllOne, Info, Manual, Cheatsheet, J1, Template

categories:                             [ Manual ]
tags:                                   [ Cheatsheet, JekyllOne, Template ]

image:
  path:                                 /assets/images/modules/attics/1920x1280/recha-oktaviani.jpg
  width:                                1920
  height:                               1280

regenerate:                             false
permalink:                              /pages/public/tools/cheatsheet/j1/

resources:                              [ animate, clipboard, rouge ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/recha-oktaviani.jpg
          alt:                          Photo by Recha Oktaviani on Unsplash
          badge:
            type:                       unsplash
            author:                     Recha Oktaviani
            href:                       https://unsplash.com/de/@rechaoktaviani
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="dropcap"]
The Cheatsheet discusses management commands for daily use. The Template
system J1 is a creation tool to build simple but fully configurable modern
static websites using the generator _Jekyll_. No deep knowledge of using
_Jekyll_ is needed for the template system _J1_.

J1 Templated provides a handy command, `j1`, to manage and run websites
created by Jekyll One. Find all commands supported below.

CAUTION: The command `j1` is a *wrapper* around the *top-level* scripts
defined in the _NodeJS_ project file `package.json`. To run a J1 project,
an installation of _NodeJS_ is *required*.

.Project Management commands
[cols="2a, 5a, 5a", options="header", width="100%", role="rtable mt-3 mb-5"]
|===
|Command |Description |Example

|`app`
|Run the website of a J1 project as a standalone *web application*. In
difference to the command `j1 site`, the web application does *not* use
_Jekyll_ to serve the web. The application use the web server _Puma_ based
on web *root* folder `_site` located in the project.
|
[source, sh]
----
j1 app
----

NOTE: To run a project as a standalone web application, a previous `setup`
is *required* to serve the site out of the `_site` folder.

|`generate`
|Creates a J1 project *scaffold* in folder `<project name>`. When the
scaffold is created, change to that (project-)folder and run `j1 setup` to
make the project ready to use.
|
[source, sh]
----
j1 generate <project name>
----

|`help`
|Show the help message, optionally for a given *subcommand* (e.g. generate).
|
[source, sh]
----
j1 help
j1 help generate
----

|`patch`
|Install available patches for a J1 project. For default, patches are
installed *userized* in the users `gem` folder `~/.gem`. +
See more details running `j1 help patch`.
|
[source, sh]
----
j1 patch
----

NOTE: Installing patches are only required for the _Windows_ platform and
installed automatically if a project is being *generated*. For _Linux_ or
_OSX_ platforms, the installation of patches is *skipped*.

|`rebuild`
|Rebuild a all *sources* of a project. If you run a website in *development*
mode (`j1 site`), most of the changes of your content (source) is detected
*automatically* and *rebuild*.
|
[source, sh]
----
j1 rebuild
----

CAUTION: Fundamental changes of the configuration like the *site* config
`_config.yml` (Jekyll) affect your web's base settings, and a `rebuild`
is *required* to apply those changes.

|`reset`
|Reset a J1 project to factory state. A reset of a project removes all
*project* related files but all *sources* of a web are *untouched*.
|
[source, sh]
----
j1 reset
----

|`setup`
|Initialize a J1 project scaffold for first use. The management of a J1
site requires _NodeJS_ libraries and larger number of _Ruby_ GEM files
(_Ruby_ libraies) to be installed and initialized.
|
[source, sh]
----
j1 setup
----

|`site`
|Run the web site of a J1 project in *development* mode. For development,
the site generator of _Jekyll_ is running in background to detect changes
on your site *sources*.
|
[source, sh]
----
j1 site
----

NOTE: The generator of _Jekyll_ is running in `incremental` mode and rebuild
modified source files automatically. If the base configuration of a website
is changed, a rebuild of the web is required. +
See command `rebuild` for more details.

|===
