---
title:                                  Persönliche Daten
tagline:                                ihre privatsphäre
date:                                   2023-01-01 01:00:00 +100
description: >
                                        Description has to be placed here

categories:                             [ Site ]
tags:                                   [ Privatsphäre ]

robots:
  index:                                false
  follow:                               false

sitemap:                                false
exclude_from_search:                    true

fam_menu_id:                            page_ctrl_simple
scrollbar:                              false
comments:                               false
toc:                                    true

permalink:                              /pages/public/legal/de/privacy/
regenerate:                             false

resources:                              []
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/modules/attics/markus-spiske-1920x1280.jpg
          alt:                          Photo by Markus Spiske on Unsplash
          badge:
            type:                       unsplash
            author:                     Markus Spiske
            href:                       https://unsplash.com/@markusspiske
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:legal-warning:                         false

// Attribute settings for section control
//
:cookies:                               true
:cookie-consent:                        true
:logs-files:                            false
:google-analytics:                      true
:hyvor:                                 true
:facebook:                              false
:twitter:                               false
:instagram:                             false
:youtube:                               true
:vimeo:                                 true

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ifeval::[{legal-warning} == true]
WARNING: This document *does not* constitute any *legal advice*. It is
highly recommended to verify legal aspects and implications.
endif::[]

// Include sub-documents
// -----------------------------------------------------------------------------
Die Betreiber dieser Website nehmen den Schutz Ihrer persönlichen Daten ernst.
Wir behandeln Ihre Daten vertraulich und halten uns zum Schutz Ihrer
Privatsphäre an die Datenschutz-Grundverordnung (DSGVO) der Europäischen Union.

ifeval::[{cookies} == true]
== Cookies

Diese Website verwendet Cookies und ähnliche Technologien für den Betrieb
dieses Angebots. Es steht Ihnen frei Ihre Einwilligung zu erteilen, zu
verweigern oder zu widerrufen indem Sie im Datenschutzdialog auf
die Schaltfläche *Einstellungen* klicken. Nachträgliche Änderungen sind
*jederzeit* durch Klick auf die Ikone mdi:cookie[18px, md-blue]
in der *Menüleiste* möglich.

*Erweiterte* Cookies von Drittanbietern werden nur mit Ihrer Zustimmung
verwendet. Diese zusätzlichen Cookies werden verwendet, um die Nutzung dieser
Website zu analysieren oder personalisierte Inhalte anzubieten. Die Auswertung
dieser Informationen bietet Ihnen eine bessere Benutzererfahrung der angebotenen
Seiten wie zusätzliche Funktionen der jeweiligen Anbieter. Mehr Informationen
finden Sie im Datenschutzdialog durch Anklicken der Schaltfläche
*Datenschutzerklärung* oder in den folgenden Abschnitten der jeweiligen
Anbieter.

Notwendig::
Notwendige Daten werden in Cookies gespeichert, um die Basisdienste dieser Site
zu betreiben. Diese Website führt *keine Aufzeichnungen* über deren Nutzung.
Alle Informationen (Daten) die zur Steuerung dieser Seite notwendig sind,
werden in sogenannten *Sitzungscookies* (Session Cookies) gespeichert.
Sitzungscookies werden von Ihrem Browser *automatisch* entfernt, wenn Sie alle
Fenster in Ihrem Browser *schließen*.

Analysen::
Analysen der Nutzung dieser Website hilft uns, Ihr Nutzungserlebnis der Website
zu optimieren. Zur Analyse wird Google Analytics (GA) verwendet. Diese Website
übermittelt keine personenbezogenen Daten. Implizite personenbezogene
Daten wie IP-Adressen werden zum Schutz Ihrer Privatsphäre *anonymisiert*.

Personalisierung::
Personalisierung wird verwendet um beispielsweise Benutzerfeedback zu sammeln,
zusätzliche Funktionen anzubieten oder Werbekampagnen durchzuführen. Einnahmen
aus Werbekampagnen erlauben es uns Ihnen diese Website kostenlos zur Verfügung
zu stellen. Partner ermöglichen es uns, Ihnen exzellente personalisierte
Dienste anzubieten sowie die Kosten für den Betrieb dieser Website zu
finanzieren.

endif::[]


ifeval::[{cookie-consent} == true]
== Datenschutz und Ihre Einstellungen

Wenn Sie einstellen möchten welche *Cookies* und ähnliche Technologien
über *diese Site* verwendet werden, können Sie Ihre Einwilligung anpassen.
Außerdem Sie können Sie Cookies ablehnen, indem Sie Ihre *Browser*
Einstellungen entsprechend anpassen. Bitte seien Sie vorsichtig, wenn Sie Ihre
Browsereinstellungen ändern. Die Ablehnung von Cookies kann zu schwerwiegenden
Problemen beim Besuch von Websites führen, die von Gebrauch von Cookies
abhängen. Dies betrifft nicht nur die Seiten dieses Angebots.

NOTE: Haben Sie zuvor unsere Website besucht und der Verwendung von Cookies
zugestimmt, können sich die zudem Zeitpunkt erstellten Cookies noch auf Ihrem
System befinden. In diesem Fall sind möglicherweise bereits vorhandene Cookies
*manuell* über Funktionen Ihres Browsers zu löschen.

++++
<div class="mt-4 mb-3">
  <a  href="javascript:j1.cookieConsent.showDialog()"
      class="btn btn-primary btn-lg btn-block btn-raised btn-flex mb-3"
      aria-label="Cookie Consent"
      style="min-width: 25rem">
      <i class="mdi mdi-cookie mdi-2x mr-2"></i>
      Ihre Einstellungen
  </a>
</div>
++++
endif::[]

ifeval::[{logs-files} == true]
== Log files

Wir sammeln bestimmte Informationen automatisch von unseren Webservern und
speichern sie in Protokolldateien. Diese Informationen können Internet Protocol
(IP)-Adressen, Browsertyp, Internet Service Provider (ISP), Verweis- und
Ausstiegsseiten, Betrieb System-, Zeitstempel und/oder Clickstream-Daten.

Diese sind:

* Browsertyp und -Version
* Betriebssystem
* Referrer-URL
* Hostname
* Zeitstempel der Seitenaufrufe

Wir können diese Protokollinformationen mit anderen Informationen kombinieren.
Wir tun dies, um die von uns angebotenen Dienstleistungen zu verbessern und das
Angebot auf unseren Seiten zu verbessern.

endif::[]

ifeval::[{google-analytics} == true]
== Verwendung von Analysen (GA)

Diese Website benutzt Google Analytics (GA), ein Datendienst zur Auswertung
von Benutzeraktivitäten. Diese Funktion wird nur verwendet, falls Sie in den
Einstellungen zu Ihrer Privatsphäre *Analysen* zugestimmt haben.
Dieser Dienst wird angeboten durch:

----
   Google Inc.
   1600 Amphitheatre Parkway Mountain View
   CA 94043
   USA
----

Der Service verwendet sogenannte Cookies. Das sind Textdateien, die auf
Ihrem Computer gespeichert werden, um die Nutzung der Website durch die
Benutzer auszuwerten. Die durch Cookies erzeugten Informationen werden
übermittelt und auf Servern des Unternehmens gespeichert.

Diese Webseite verwendet die *Anonymisierung* von *IP-Adressen*. Damit wird
Ihre Netzwerk-Adresse im Bereich der Mitgliedsstaaten der Europäischen Union
sowie anderen Vertragsparteien des Abkommens über den Europäischen
Wirtschaftsraum *gekürzt* und eine *persönliche* Zuordnung der erfassten Daten
ist *nicht* möglich.

Weitere Informationen hierzu finden Sie in den Richtlinen zum
link:{url-google--privacy-policy-de}[Datenschutz, {browser-window--new}].

NOTE: Sie können der Verwendung jederzeit widersprechen, indem Sie die
entsprechenden Einstellungen zu Ihrer Privatsphäre auswählen. Beachten Sie
jedoch bitte, dass Sie in diesem Fall möglicherweise nicht in der Lage sind
die volle Funktionalität dieser Website zu nutzen.

endif::[]

ifeval::[{hyvor} == true]
== Verwendung von Kommentaren (HT)

Auf unseren Seiten *können* Funktionen des Dienstes *Hyvor Talk* (HT)
eingebunden sein. Diese Funktionen (Kommentare/Chats) stehen zur Verfügung,
falls Sie in den Einstellungen zu Ihrer Privatsphäre der *Personalisierung*
zugestimmt haben.
Dieser Dienst wird angeboten durch:

----
Green Mount State
Madawa, Pilessa No 130
Kurunegala
Sri Lanka
----

Die *Kosten* für die Bereitstellung des Dienstes werden durch den *Betreiber*
dieser Website *übernommen*. Die Services von *Hyvor Talk* stellen die Sicherung
Ihrer Privatsphäre in den Vordergrund (*Privacy First*). Wenn Sie unsere Website
besuchen, wird die Kommentarplattform eine direkte Verbindung zwischen Ihrem
Browser und den Servern  des Unternehmens *Hyvor* herstellen.

Über die Kommentar-Funktion werden *keine* Tracking-, Werbe-, Affiliate-
oder sonstige Kodes von *Drittanbietern* plaziert. Personenbezogene Daten
werden zu *keiner Zeit* an Dritte weitergegeben.

Der Service verwendet sogenannte Cookies. Das sind Textdateien, die auf
Ihrem Computer gespeichert werden um die Nutzung des Dienstes durch die
Benutzer auszuwerten. Die durch Cookies erzeugten Informationen werden
übermittelt und auf Servern des Unternehmens gespeichert.

Weitere Informationen hierzu finden Sie in den Richtlinen zum
https://hyvor.com/privacy-policy[Datenschutz, {browser-window--new}].

NOTE: Sie können der Verwendung jederzeit widersprechen, indem Sie die
entsprechenden Einstellungen zu Ihrer Privatsphäre auswählen. Beachten Sie
jedoch bitte, dass Sie in diesem Fall möglicherweise nicht in der Lage sind
die volle Funktionalität dieser Website zu nutzen.

endif::[]


ifeval::[{facebook} == true]
== Verwendung der Facebook-Integration

Auf unseren Seiten *können* Funktionen des sozialen Netzwerks *Facebook*
eingebunden sein. Diese Funktionen stehen zur Verfügung, falls Sie in den
Einstellungen zu Ihrer Privatsphäre der *Personalisierung* zugestimmt haben.
Diese Funktionen werden angeboten durch:

----
  Facebook Inc.
  1 Hacker Way Menlo Park
  CA 94025
  USA
----

Wenn Sie unsere Website besuchen, wird über eine Integration (*Like-Button*)
eine direkte Verbindung zwischen Ihrem Browser und den Servern des Unternehmens
Facebook aufgebaut. Dadurch werden persönliche Daten an die Server des
Unternehmens *Facebook* übertragen. Voraussetzung hierzu ist, dass Sie während
des Besuchs unserer Seiten *bereits* mit Ihrem persönlichen Benutzer-Konto
des sozialen Netzwerks *eingeloggt sind*.

Durch klicken auf den *Like-Button* können Sie die Inhalte unserer Seiten mit
Ihrem Benutzer-Profil verbinden und damit den Besuch unserer Seiten Ihrem
Benutzerkonto zuordnen.

Die Integration der Inhalte verwendet sogenannte Cookies. Das sind Textdateien,
die auf Ihrem Computer gespeichert werden um die Nutzung des Dienstes durch die
Benutzer auszuwerten. Die durch Cookies erzeugten Informationen werden
übermittelt und auf Servern des Unternehmens gespeichert.

Wir weisen darauf hin, dass wir als Anbieter keine Kenntnis von Inhalt der
übermittelten Daten sowie deren Nutzung haben. Weitere Informationen zu diesem
Thema finden Sie in der Datenschutzerklärung des Anbieters unter
link:{url-facebook--privacy-policy-en}[Datenschutz, {browser-window--new}].

Wenn Sie *nicht* möchten, dass das Unternehmen Facebook den Besuch
unserer Website mit Ihrem Benutzerkonto zuordnen kann, loggen Sie sich bitte
aus Ihrem Benutzer-Konto aus *bevor* Sie unsere Website besuchen.

NOTE: Sie können der Verwendung jederzeit widersprechen, indem Sie die
entsprechenden Einstellungen zu Ihrer Privatsphäre auswählen. Beachten Sie
jedoch bitte, dass Sie in diesem Fall möglicherweise nicht in der Lage sind
die volle Funktionalität dieser Website zu nutzen.

endif::[]

ifeval::[{twitter} == true]
== Verwendung der Twitter-Integration

Auf unseren Seiten *können* Funktionen des Nachrichten-Netzwerks *Twitter*
eingebunden sein. Diese Funktionen stehen zur Verfügung, falls Sie in den
Einstellungen zu Ihrer Privatsphäre der *Personalisierung* zugestimmt haben.
Diese Funktionen werden angeboten durch:

----
  Twitter Inc.
  1355 Market Street Suite 900
  CA 94103
  USA
----

Wenn Sie unsere Website besuchen, wird über eine Integration (*Re-Tweet*)
eine direkte Verbindung zwischen Ihrem Browser und dem Servern des Unternehmens
*Twitter* aufgebaut. Dadurch werden persönliche Daten an die Server des
Unternehmens *Twitter* übertragen. Voraussetzung hierzu ist, dass Sie während
des Besuchs unserer Seiten bereits mit Ihrem persönlichen Benutzer-Konto
des Nachrichten-Netzwerks eingeloggt sind.

Die Integration der Inhalte verwendet sogenannte Cookies. Das sind Textdateien,
die auf Ihrem Computer gespeichert werden um die Nutzung des Dienstes durch die
Benutzer auszuwerten. Die durch Cookies erzeugten Informationen werden
übermittelt und auf Servern des Unternehmens gespeichert.

Wir weisen darauf hin, dass wir als Anbieter keine Kenntnis von Inhalt der
übermittelten Daten sowie deren Nutzung haben. Weitere Informationen zu diesem
Thema finden Sie in der Datenschutzerklärung des Abieters unter
link:{url-twitter--privacy-policy-en}[Datenschutz, {browser-window--new}].

NOTE: Sie können der Verwendung jederzeit widersprechen, indem Sie die
entsprechenden Einstellungen zu Ihrer Privatsphäre auswählen. Beachten Sie
jedoch bitte, dass Sie in diesem Fall möglicherweise nicht in der Lage sind
die volle Funktionalität dieser Website zu nutzen.

endif::[]

ifeval::[{instagram} == true]
== Verwendung der Instagram-Integration

Auf unseren Seiten *können* Funktionen des sozialen Netzwerks *Instagram*
eingebunden sein. Diese Funktionen stehen zur Verfügung, falls Sie in den
Einstellungen zu Ihrer Privatsphäre der *Personalisierung* zugestimmt haben.
Diese Funktionen werden angeboten durch:

----
  Instagram Inc.
  1601 Willow Road Menlo Park
  CA 94025
  USA
----

Wenn Sie unsere Website besuchen, wird über eine Integration (*Instagram Button*)
eine direkte Verbindung zwischen Ihrem Browser und dem Servern des Unternehmens
*Instagram* aufgebaut. Dadurch werden persönliche Daten an die Server des
Unternehmens *Instagram* übertragen. Voraussetzung hierzu ist, dass Sie während
des Besuchs unserer Seiten bereits mit Ihrem persönlichen Benutzer-Konto
des Nachrichten-Netzwerks eingeloggt sind.

Wenn Sie in Ihrem Instagram Benutzer-Konto eingeloggt sind können Sie
durch Anklicken des *Instagram Buttons* die Inhalte unserer Seiten mit
Ihrem *Instagram Profil* verlinken. Dadurch kann Instagram den Besuch unserer
Seiten Ihrem Benutzerkonto zuordnen. Wir weisen darauf hin, dass wir als
Anbieter der Seiten keine Kenntnis vom Inhalt der übermittelten Daten sowie
deren Nutzung durch Instagram erhalten.

Die Integration der Inhalte verwendet sogenannte Cookies. Das sind Textdateien,
die auf Ihrem Computer gespeichert werden um die Nutzung des Dienstes durch die
Benutzer auszuwerten. Die durch Cookies erzeugten Informationen werden
übermittelt und auf Servern des Unternehmens gespeichert.

Weitere Informationen hierzu finden Sie in den Richtlinen zum
link:{url-instagram--privacy-policy}[Datenschutz, {browser-window--new}].

Wenn Sie *nicht* möchten, dass das Unternehmen Instagram den Besuch
unserer Website mit Ihrem Benutzerkonto zuordnen kann, loggen Sie sich bitte
aus Ihrem Benutzer-Konto aus *bevor* Sie unsere Website besuchen.

NOTE: Sie können der Verwendung jederzeit widersprechen, indem Sie die
entsprechenden Einstellungen zu Ihrer Privatsphäre auswählen. Beachten Sie
jedoch bitte, dass Sie in diesem Fall möglicherweise nicht in der Lage sind
die volle Funktionalität dieser Website zu nutzen.

endif::[]


ifeval::[{youtube} == true]
== Verwendung von Videos (YT)

Auf unseren Seiten *können* Funktionen (Player) der Video-Plattform *YouTube*
(YT) eingebunden sein. Diese Funktionen stehen zur Verfügung, falls Sie in den
Einstellungen zu Ihrer Privatsphäre der *Personalisierung* zugestimmt haben.
Diese Funktionen werden angeboten durch:

----
  Google Ireland Limited
  Gordon House, Barrow Street
  Dublin 4
  Irland
----

Wenn Sie unsere Website besuchen, wird über eine Integration (*Player*)
eine direkte Verbindung zwischen Ihrem Browser und dem Servern des Unternehmens
*YouTube* aufgebaut. Dadurch werden neben Inhalten (Videos) auch persönliche
Daten an die Server des Unternehmens *YouTube* übertragen.

Die Integration der Inhalte verwendet sogenannte Cookies. Das sind Textdateien,
die auf Ihrem Computer gespeichert werden um die Nutzung des Dienstes durch die
Benutzer auszuwerten. Die durch Cookies erzeugten Informationen werden
übermittelt und auf Servern des Unternehmens gespeichert.

Wir weisen darauf hin, dass wir als Anbieter keine Kenntnis von Inhalt der
übermittelten Daten sowie deren Nutzung haben. Weitere Informationen zu diesem
Thema finden Sie in der Datenschutzerklärung des Anbieters unter
link:{url-google--privacy-policy-de}[Datenschutz, {browser-window--new}].

NOTE: Sie können der Verwendung jederzeit widersprechen, indem Sie die
entsprechenden Einstellungen zu Ihrer Privatsphäre auswählen. Beachten Sie
jedoch bitte, dass Sie in diesem Fall möglicherweise nicht in der Lage sind
die volle Funktionalität dieser Website zu nutzen.

endif::[]

ifeval::[{vimeo} == true]
== Verwendung von Videos (VI)

Auf unseren Seiten *können* Funktionen (Player) der Video-Plattform *Vimeo*
(VI) eingebunden sein. Diese Funktionen stehen zur Verfügung, falls Sie in den
Einstellungen zu Ihrer Privatsphäre der *Personalisierung* zugestimmt haben.
Diese Funktionen werden angeboten durch:

----
  Vimeo Inc.
  555 West 18th Street
  NY 10011
  USA
----

Wenn Sie unsere Website besuchen, wird über eine Integration (*Player*)
eine direkte Verbindung zwischen Ihrem Browser und dem Servern des Unternehmens
*Vimeo* aufgebaut. Dadurch werden neben Inhalten (Videos) auch persönliche
Daten an die Server des Unternehmens *Vimeo* übertragen.

Die Integration der Inhalte verwendet sogenannte Cookies. Das sind Textdateien,
die auf Ihrem Computer gespeichert werden um die Nutzung des Dienstes durch die
Benutzer auszuwerten. Die durch Cookies erzeugten Informationen werden
übermittelt und auf Servern des Unternehmens gespeichert.

Wir weisen darauf hin, dass wir als Anbieter keine Kenntnis von Inhalt der
übermittelten Daten sowie deren Nutzung haben. Weitere Informationen zu diesem
Thema finden Sie in der Datenschutzerklärung des Anbieters unter
link:{url-vimeo--privacy-policy}[Datenschutz, {browser-window--new}].

NOTE: Sie können der Verwendung jederzeit widersprechen, indem Sie die
entsprechenden Einstellungen zu Ihrer Privatsphäre auswählen. Beachten Sie
jedoch bitte, dass Sie in diesem Fall möglicherweise nicht in der Lage sind
die volle Funktionalität dieser Website zu nutzen.

endif::[]
