---
title:                                  Kommentare
tagline:                                Mit Respekt Diskutieren
date:                                   2023-01-01 01:00:00 +100
description: >
                                        Wir schätzen Kommentare und bedanke uns für die Zeit der Besucher die Ihre
                                        Ideen auszutauschen und Feedback geben. Vielen Dank an Alle die einen
                                        Kommentar schreiben.

categories:                             [ Site ]
tags:                                   [ Kommentare, Richtlinien ]

image:
  path:                                 /assets/images/modules/attics/1920x1280/j1-theme-mockup-1.jpg
  width:                                1920
  height:                               1280
  alt:                                  J1 Themes Mockup

robots:
  index:                                false
  follow:                               false

sitemap:                                false
exclude_from_search:                    true
fab_menu_id:                            page_ctrl
scrollbar:                              false
comments:                               false
toc:                                    true

permalink:                              /pages/public/legal/de/comment_policy/
regenerate:                             false

resources:                              [ animate, clipboard, rouge ]
resource_options:
  - attic:
      padding_top:                      600
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/j1-theme-mockup-1.jpg
          alt:                          J1 Themes Mockup
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
Wir schätzen Kommentare und bedanke uns für die Zeit der Besucher die Ihre
Ideen auszutauschen und Feedback geben. Vielen Dank an Alle die einen
Kommentar schreiben.

== Kommentare sind willkommen

Kommentare sind auf dieser Seite willkommen und erwünscht. Aber es gibt einige
Fälle in denen Kommentare bearbeitet oder gelöscht werden. Wir behalten uns das
Recht vor, übermittelte Kommentare ohne vorherige Ankündigung zu bearbeiten
oder zu löschen.

NOTE: Die Kommentarrichtlinie kann jederzeit geändert werden.

Werbung und Spam::
Das Einfügen von Links zu relevanten Inhalten ist erwünscht. Jedoch sollen
Kommentare wie deren Verweise zum Thema des jeweiligen Beitrags passen.
Kommentare die als automatisierter Inhalt erkannt werden (Spam) oder rein
werbender Natur gelten werden gelöscht.

Schimpfwörter::
Kommentare mit Schimpfwörtern werden gelöscht.

Grobe Sprache::
Kommentare die Sprache verwenden die als anstößig angesehen werden können
werden gelöscht. Dazu zählen beleidigende, bedrohende, pornografische,
irreführende oder verleumderische Anmerkungen.

Angriffe::
Kommentare die Personen, oder generell Menschen, direkt angreifen werden
gelöscht.

Belästigung::
Kommentare die andere Besucher, oder generell Menschen, belästigen können
werden gelöscht. Alle Kommentare sollen respektvoll sein.

Anonymität::
Es werden nur Kommentare von Personen akzeptiert die sich persönlich
identifizieren.
