---
title:                                  Biography
title_extention:                        Collections are Jekyll's most powerful feature
tagline:                                Today's People

date:                                   2023-01-29
#last_modified:                         2023-01-01

description: >
                                        Today's people is a collection contains the biography's
                                        of celebrities well known by most of us. Find the books issued
                                        by musicans, actors and more.
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap,
                                        collections

categories:                             [ Books ]
tags:                                   [ Biography, Preview ]

image:
  path:                                 /assets/images/modules/attics/giammarco-boscaro-1920x1280.jpg
  width:                                1920
  height:                               1280

toc:                                    false
fab_menu_id:                            default
regenerate:                             false
permalink:                              /pages/public/learn/bookshelf/article_previewer/biography/

resources:                              [ animate, masonry, rouge ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/images/modules/attics/giammarco-boscaro-1920x1280.jpg
          alt:                          Photo by Giammarco on Unsplash
          badge:
            type:                       unsplash
            author:                     Giammarco
            href:                       //unsplash.com/@giamboscaro
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set page (local) attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

{% comment %} Liquid procedures
-------------------------------------------------------------------------------- {% endcomment %}
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}
{% capture create_collection_article_preview %}themes/{{site.template.name}}/procedures/collections/create_collection_article_preview.proc{% endcapture %}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="none" %}

{% comment %} Debugging
-------------------------------------------------------------------------------- {% endcomment %}
{% comment %} site.biography: {{ site.biography | debug }} {% endcomment %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Find below all available articles the `Booskhelf` collections contains.
The content is automatically generated and taken from the articles the
collections contains.

[NOTE]
====
*Resize* the browser window to see the `masonry` module, applied on
this page, in action. All elements gets automatically *re-ordered* to fit
the grid positions calculated by the module.
====

mdi:clock-time-five-outline[24px, md-gray mr-2]
*5 Minutes* to read

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== Available Books

Find below all available articles in the `biography` collection. The content
is automatically generated and taken from the articles this collection
contains.

A biography is a written account of a person's life, typically focusing on
major achievements, events, and experiences. It can be a detailed record of
a person's life, covering everything from their birth and childhood to their
personal and professional accomplishments and even their death.

[role="mb-4"]
Biographies can be written by someone or someone else and found in various
formats, including books, articles, and online sources. A biography aims to
provide insight into a person's life, personality, and achievements and to
inspire and inform readers about their accomplishments and contributions
to society.

.Collection Biography
masonry::collection_biography[role="notoc mb-7"]

////
++++
<div class="row mb-4">
  <div class="col-md-12 col-xs-12">
    {% include {{create_collection_article_preview}} collection=site.biography %}
  </div>
</div>
++++
////
