---
title:                                  Tester
tagline:                                sidebar
date:                                   2020-11-03 00:00:00 +100
description: >
                                        Welcome to the preview page focussing on the image module. This page
                                        shows some valuable features of the J1 Template to manage your image-based
                                        content using lightboxes, carousels (slider), and galleries.

categories:                             [ Testpages ]
tags:                                   [ Example ]

comments:                               false
fab_menu_id:                            page_ctrl_simple

permalink:                              /pages/public/learn/side_bar_tester/
regenerate:                             false

resources:                              [
                                          clipboard, rouge, carousel, lightbox,
                                          justifiedGallery, lightGallery
                                        ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/pages/roundtrip/images-1920x1280-bw.jpg
          alt:                          Photo by Ricardo Gomez Angel on Unsplash
          badge:
            type:                       unsplash
            author:                     Ricardo Gomez Angel
            href:                       https://unsplash.com/@ripato/portfolio
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Include sub-documents (if any)
// -----------------------------------------------------------------------------

Welcome to the first preview page focussing on the image module. This page
shows some valuable features of the J1 Template to manage your image-based
content using lightboxes, carousels (slider), and galleries.

The image module offers complex functionality based on powerful OpenSource
libraries like JustifiedGallery for high-end, masonry-styled preview maps.
J1 Template uses the jQuery plugin Owl Carousel as a base for image sliders.
A carousel app (slider) lets you present your images as shows.

Lightboxes like LightGallery or Lightbox V2 support your web for enlarged
image views of your picture or video content. Have a look, a quick tour
of what J1 can do for image data. Have fun!

== J1 Lightboxes

A Lightbox, in general, is a helper which displays enlarged, almost
screen-filling versions of pictures (or videos) while dimming the rest of the
page. The technique, introduced by Lightbox V2, gained widespread popularity
due to its simple and elegant style. The term lightbox is used since then for
Javascript libraries to support such functionality.

For the J1 Template, two different lightboxes can be used:

* Lightbox V2 (lightbox)
* LightGallery

The default lightbox used by J1 Template is Lightbox V2, a Javascript library
written by _Lokesh Dhakar_. The name of that (build-in) is simply: lightbox.
For more complex use cases, like a thumbnail gallery preview or video support,
LightGallery can be used alternatively.

NOTE: The name LightGallery implies a sort of a Gallery, but the library is a
_lightbox_. And, LightGallery provides much more functionality on image-based
data rather than enlarged displaying of images. See the examples below to check
for the differences in comparison to the simpler Lightbox V2 lightbox.

Both lightboxes are fully integrated to be used as standalone modules or
used as helpers *under-the-hood* by other apps or modules focussing on
image-data like gallery or carousel, the build-in carousel module.

== Lightbox Examples

Find below an example of using the lightbox Lightbox standalone. See how
single (individual) images are linked for use with Lightbox.

.Lightbox block for standalone images
lightbox::example-standalone[ 400, {data-images-standalone} ]

Lightbox supports image groups (image sets). Click on the images below to
see how Lightbox manages a group of images.

.Lightbox block for grouped images
lightbox::example-group[ 400, {data-images-group}, group ]

=== LightGallery Example

LightGallery provides more complex functions on image data. The module
supports a gallery-style thumbnail preview plus image resizing, a download
dialog, sharing provider support, and some more helpful. Check what
LightGallery can do by the following example.

gallery::jg_old_times[]


++++

<button class="btn u-sidebar-navigation__toggler" id="sideNav-toggler" aria-haspopup="true" aria-expanded="false" aria-controls="sideNav" aria-label="Toggle Header" data-bs-target="#sideNav" style="display: block;">
<i id="fam-icon" class="mdi mdi-wrap mdi-"></i>
</button>

<style>

/* Sidebar shortcode navigation styles */
/*------------------------------------
  Sidebar Navigation
------------------------------------*/
@media all and (min-width: 992px) {
  .u-sidebar-navigation {
    position: fixed;
    top: 0;
    left: -21.42857rem;
    width: 300px;
  }
}

/*
.u-sidebar-navigation-inner {
  background-color: #1c2434;
  color: #fff;
  padding: 20px 0;
}

.u-sidebar-navigation__search-input {
  border-radius: 3px;
  border: none;
}

.u-sidebar-navigation .nav-link {
  color: #fff;
  padding: 0.5rem 1.42857rem;
}

.u-sidebar-navigation .nav-link:hover {
  background-color: rgba(255, 255, 255, 0.15);
}

.u-sidebar-navigation .nav-link.active {
  background-color: rgba(255, 255, 255, 0.1);
}

*/
.u-sidebar-navigation__toggler {
  position: fixed;
  top: 120px;
  left: 0;
  width: 53px;
  height: 53px;
  background-color: #1c2434;
  color: #fff;
  border-radius: 0 3px 3px 0;
  font-size: 22px;
  z-index: 2;
}

.u-sidebar-navigation__toggler:hover, .u-sidebar-navigation__toggler:focus {
  color: #fff;
}

/*
.u-sidebar-navigation__closer {
  position: absolute;
  top: 22px;
  right: 15px;
  width: 25px;
  height: 25px;
  padding: 0;
  color: #fff;
  background-color: transparent;
  z-index: 3;
}

.u-sidebar-navigation__closer:hover, .u-sidebar-navigation__closer:focus {
  color: #fff;
}

@media all and (max-width: 992px - 1) {
  .u-sidebar-navigation-list {
    display: block;
    -webkit-columns: 4;
            columns: 4;
  }
  .u-sidebar-navigation-list .dropdown-toggle {
    display: none;
  }
  .u-sidebar-navigation-list .dropdown-menu {
    display: block;
    max-height: 100%;
    margin: 0;
    float: none;
    opacity: 1;
  }
}

@media all and (max-width: 768px - 1) {
  .u-sidebar-navigation-list {
    -webkit-columns: 3;
            columns: 3;
  }
}

@media all and (max-width: 576px - 1) {
  .u-sidebar-navigation-list {
    -webkit-columns: 1;
            columns: 1;
  }
}

.u-has-sidebar-navigation .u-header__overlay {
  display: none;
}
*/

</style>
++++
