---
title:                                  Tester
tagline:                                deepl
date:                                   2020-11-03 00:00:00 +100
description: >
                                        Welcome to the preview page focussing on the image module. This page
                                        shows some valuable features of the J1 Template to manage your image-based
                                        content using lightboxes, carousels (slider), and galleries.

categories:                             [ Testpages ]
tags:                                   [ Example ]

comments:                               false
fab_menu_id:                            page_ctrl_simple

permalink:                              /pages/public/learn/deepl/
regenerate:                             false

resources:                              [ clipboard, rouge, j1deepl, j1scroll ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/pages/roundtrip/images-1920x1280-bw.jpg
          alt:                          Photo by Ricardo Gomez Angel on Unsplash
          badge:
            type:                       unsplash
            author:                     Ricardo Gomez Angel
            href:                       https://unsplash.com/@ripato/portfolio
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// https://github.com/EdwardBalaj/Simple-DeepL-API-Integration

// Include sub-documents (if any)
// -----------------------------------------------------------------------------

== Deepl API V2

An integration of the DeepL API that translates a given text from one language
(default:English) to another language and outputs the translation.

++++
<div class="paragraph">
  <p>
    How do I call a function after a find for all the returned elements?
  </p>
</div>

<div>
	<form id="layout">
    <!-- Supported source languages -->
		<div id="source">
			<select id="source-language" name="source-language">
        <option selected value="auto">Auto</option>
        <option value="CS">Czech</option>
				<option value="DA">Danish</option>
        <option value="DE">German</option>
				<option value="NL">Dutch</option>
				<option value="EN">English</option>
        <option value="FR">French</option>
        <option value="EL">Greek</option>
        <option value="IT">Italian</option>
        <option value="ES">Spanish</option>
				<option value="SV">Swedish</option>
			</select>

			<textarea type="text" id="original-text"></textarea>
		</div>

		<!-- Event handler for the button (onClick) moved to JS part -->
		<input type="button" id="translate" value="Translate">

		</br>

		<!-- Supported destination languages (all) -->
		<div id="destination">
			<select id="destination-language" name="destination-language">
				<option value="BG">Bulgarian</option>
				<option value="ZH">Chinese</option>
				<option value="CS">Czech</option>
				<option value="DA">Danish</option>
				<option value="NL">Dutch</option>
				<option value="EN-US">English (American)</option>
				<option value="EN-GB">English (British)</option>
				<option value="EN">English (Others)</option>
				<option value="ET">Estonian</option>
				<option value="FI">Finnish</option>
				<option value="FR">French</option>
				<option selected value="DE">German</option>
				<option value="EL">Greek</option>
				<option value="HU">Hungarian</option>
				<option value="IT">Italian</option>
				<option value="JA">Japanese</option>
				<option value="LV">Latvian</option>
				<option value="LT">Lithuanian</option>
				<option value="PL">Polish</option>
				<option value="PT-PT">Portuguese (Portugal)</option>
				<option value="PT-BR">Portuguese (Brazilian)</option>
				<option value="PT">Portuguese (Others)</option>
				<option value="RO">Romanian</option>
				<option value="RU">Russian</option>
				<option value="SK">Slovak</option>
				<option value="SL">Slovenian</option>
				<option value="ES">Spanish</option>
				<option value="SV">Swedish</option>
			</select>

			<textarea type="text" id="translated-text"></textarea>
		</div>

	</form>
</div>
++++

++++
<style>
textarea {
	word-wrap: break-word;
	min-width: 100%;
	max-width: 100%;
	min-height: 10em;
}

select {
	display: block;
	width: 10em;
	margin: 1em 0;
}
</style>
++++

++++
<script>
  $(document).ready(function() {
    $('#translate').click(function() {
      var fromLanguage  = $('#source-language').val();
      var toLanguage    = $('#destination-language').val();

      // var paragraphs    = $('p');
      // for (para of paragraphs) {
      //   $(para).addClass('brums-content');
      // }

      // var paragraphs    =  $('#main-content').find('p');

      // $('.paragraph').find('p').each(function() {
      //   $('p').addClass('translate');
      //   $('.translate').j1deepl({
      //     auth_key: 'fe1c56dc-1342-9899-26db-c5d701791e2d:fx',
      //     source_lang: fromLanguage,
      //     target_lang: toLanguage,
      //     targetElement: '.translate'
      //   });
      //   $('.translate').j1deepl('destroy');
      // });

      // Create new translations ($objects)
      $('#original-text').j1deepl({
        api:            'pro',
        auth_key:       '1c360075-1a30-28c7-e4eb-2c0c0164ce4b',
        tag_handling:   'xml',
        ignore_tags:    'em',
        source_lang:    fromLanguage,
        target_lang:    toLanguage,
        targetElement: '#translated-text',
      });

      // $('.translate').j1deepl({
      //   auth_key: 'fe1c56dc-1342-9899-26db-c5d701791e2d:fx',
      //   source_lang: fromLanguage,
      //   target_lang: toLanguage,
      //   targetElement: '.translate'
      // });

      // destroy existing translation for next tranlations ($object)
      $('#original-text').j1deepl('destroy');
      //$('.translate').j1deepl('destroy');

     });
  });
</script>
++++
