---
title:                                  Tester
tagline:                                google translate
date:                                   2020-11-03 00:00:00 +100
description: >
                                        Welcome to the preview page focussing on the image module. This page
                                        shows some valuable features of the J1 Template to manage your image-based
                                        content using lightboxes, carousels (slider), and galleries.

categories:                             [ Testpages ]
tags:                                   [ Example ]

comments:                               false
fab_menu_id:                            page_ctrl_simple

permalink:                              /pages/public/learn/gtrans-0/
regenerate:                             false

resources:                              [
                                          clipboard, rouge, carousel, lightbox,
                                          justifiedGallery, lightGallery
                                        ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/pages/roundtrip/images-1920x1280-bw.jpg
          alt:                          Photo by Ricardo Gomez Angel on Unsplash
          badge:
            type:                       unsplash
            author:                     Ricardo Gomez Angel
            href:                       https://unsplash.com/@ripato/portfolio
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Include sub-documents (if any)
// -----------------------------------------------------------------------------

++++
<div id="google_translate_element" class="mb-5"></div>
++++

Machine translation (MT) transfers information from one language to another
by a computer without human intervention. NMT is the most advanced method
of computer-generated translations. Thanks to autonomous learning based on
artificial intelligence.

== Neural Machine Translation

Neural Machine Translation (NMT) works on a completely different principle
than previous statistics-based or rule-based machine translation methods.
The NMT uses a large neural network based on the human brain model with
the help of artificial intelligence.

The NMT is the most advanced method of computer-generated translations.
Thanks to autonomous learning based on artificial intelligence, Big Data,
and Deep Learning, this method has made enormous progress in the last recent
years. Nowadays, neural machine translation programs can be used as a basis
for professional translations.

Neural algorithms can generate accurate translations as well as *learn* a
language. This technology improves the quality of the translated data
continuously. For the NMT to work well, it must be trained to be used.
Training means that a large amount of data feeds the algorithms to
improve the reliability of the final results.

== Translation with Deepl

_Deepl_ offers one of the best NMT engines worldwide. The translater can be
used online or by an application (app) installed on a computer locally.
The third option to translate is the cloud-based service offered
by the *Deepl API* to be integrated into custom apps or websites, for example.

J1 integrates the cloud-based translator service for the *Free* service and
professional translations using the *Pro* system. The current API *version V2*
supports the translation of more than 25 languages vice versa.

Try the translator with _Jekyll One_ and _Deepl_ on your own!

++++

<!-- p><i class="flag-icon flag-icon-gr ml-3 mr-2 mb-2"></i> </p-->

<script type="text/javascript">
function googleTranslateElementInit() {
  new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
}
</script>

<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
++++
