---
title:                                  TikTok
tagline:                                video examples
date:                                   2021-04-17 00:00:00 +100
description: >
                                        Welcome to the preview page focussing on the image module. This page
                                        shows some valuable features of the J1 Template to manage your image-based
                                        content using lightboxes, carousels (slider), and galleries.

categories:                             [ TikTok ]
tags:                                   [ Video, Desktop ]

comments:                               true
fab_menu_id:                            page_ctrl_simple

personalization:                        true

permalink:                              /pages/public/tiktok/
regenerate:                             false

resources:                              [ justifiedGallery, lightGallery ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/modules/attics/franck-1920x1280.jpg
          alt:                          Photo by Franck on Unsplash
          badge:
            type:                       unsplash
            author:                     Franck
            href:                       https://unsplash.com/@franckinjapan
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="none" %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Include sub-documents (if any)
// -----------------------------------------------------------------------------

lorem:sentences[3]

lorem:sentences[5]

== Funny videos

lorem:sentences[3]

++++
<!-- See: https://forum.obsidian.md/t/how-do-i-embed-tiktok-videos/13532/13 -->
<!-- div style="max-width: 56vh;"><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 177.7778%; padding-top: 120px;"><iframe src="https://www.tiktok.com/embed/6992668750692584710" allow="fullscreen" style="position: absolute; top: 0px; left: 0px; height: 100%; width: 100%;"></iframe></div -->
<iframe loading="lazy" width="340" height="700" src="https://www.tiktok.com/embed/6726553443009383682" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="allowfullscreen"></iframe>
<iframe loading="lazy" width="340" height="700" src="https://www.tiktok.com/embed/6983746143356292357" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="allowfullscreen"></iframe>
<iframe loading="lazy" width="340" height="700" src="https://www.tiktok.com/embed/6726553443009383682" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="allowfullscreen"></iframe>

<!-- script async src="https://www.tiktok.com/embed.js"></script -->

<style>

/*
$grid-breakpoint-xl:                              1200px;
$grid-breakpoint-lg:                              992px;
$grid-breakpoint-lg-min:                          991px;
$grid-breakpoint-md:                              768px;
$grid-breakpoint-md-min:                          767px;
$grid-breakpoint-sm:                              576px;
$grid-breakpoint-xs:                              575px;
*/

.lg-tiktok {
  padding-left: 200px;
}

/* Desktop */
@media screen and (min-width: 991px) {
  .lg-tiktok {
    padding-left: 300px;
  }
}


/* iPad */
@media screen and (max-width: 1024px) {
  .lg-tiktok {
    padding-left: 40px;
  }
}

/* Mobile */
@media screen and (max-width: 575px)  {
  .lg-tiktok {
    padding-left: 20px;
  }
 }

/*
 @media screen and (max-width: 575px)  {
   .lg-tiktok {
     padding-left: 180px;
   }
  }
*/

</style>
++++

// .TikTok
// gallery::jg_tiktok[role="mb-5"]
