// ~/document_base_folder/_includes/documents/100_chapter/
// Chapter document: 100_chapter_document.asciidoc
// -----------------------------------------------------------------------------

== Chapter 1

J1 Template support popular icons font sets out-of-the-box:

* link:{url-mdi--home}[Material Design Icons, {browser-window--new}] (MDI)
* link:{url-fontawesome--home}[FontAwesome Icons V5, {browser-window--new}] (FA)
* link:{url-iconify--home}[Iconify Icons, {browser-window--new}] (II)

The icon sets MDI and FA are very good in design and have a rich set of
different icons for many categories used for the Web. See below some details
for link:{url-roundtrip--mdi-icons}[Material Design Icons, {browser-window--new}]
and link:{url-roundtrip--fontawesome-icons}[FontAwesome Icons, {browser-window--new}].

Iconify icons is not a locally stored icon-set like MDI or FA. All icons are
loaded over the Internet using the so-called *Unified OpenSource Icon
Framework*. See section link:{url-roundtrip--iconify-icons}[Iconify Icons, {browser-window--new}]
for more information.
