// ~/document_base_folder/_includes/documents/100_chapter/
// Chapter document: 110_chapter_document.asciidoc
// -----------------------------------------------------------------------------

=== Section

The primary icon-set for J1 Template is
link:{url-mdi--home}[Material Design Icons, {browser-window--new}],
because it is extremely rich set providing more than 5900+ icons for the
current version (v5.9.55). From a design perspective, _MDI_ has an excellen
*Material Design* support an comes with the original icon set created by
_Google_ build-in.

_Material Design Icons_ (MDI) is a beneficial design resource for Web Design
that is based on _Google_'s Material Design. _MDI_ is a community-driven
project to create an increased number of icons based on _Google_'s official
repository and MD style specification.

==== Subsection

_MDI_ is a growing collection to allow designers and developers targeting
various platforms to download icons in the format, color and size they need
for any project. The repo contains today 2100+ icons plus converted icons from
the official set created by _Google_.

// include::{documentdir}/tables/110_material_design_icons.asciidoc
// include::{tabledir}/110_material_design_icons.asciidoc
include::../tables/110_material_design_icons.asciidoc[]

NOTE: Using Material Design Icons with Asciidoc is quite easy as an inline
macro `mdi:` is available to place icons where ever you want. See more about
this in section
link:{url-roundtrip--asciidoc-extensions}#icon-fonts[Asciidoc Extensions, {browser-window--new}]

_J1 Template_ supports the full set of _MDI_ for the Web (Webfont, WOFF). The
icon set is fully integrated and can be used out-of-the-box.
