---
title:                                  Multi Document
tagline:                                Manage High Number Of Chapters

date:                                   2022-01-01
#last_modified:                         2023-01-01

description: >
                                        J1 Template is a Bootstrap V5 website template for the static
                                        site generator Jekyll.
                                        Multi-chapter documents are used for more complex articles of a website. If
                                        the number of chapters is or exceeds three for an article, it could make sense
                                        to split larger documents chapter-wise into separate files. This document
                                        type is based on multiple Asciidoc documents and make use of (local and
                                        global) Asciidoc include files and attributes.

categories:                             [ Knowledge, Asciidoc ]
tags:                                   [ Skeleton, MultiDocument ]

robots:
  index:                                false
  follow:                               false

image:
  path:                                 /assets/image/module/attic/sigmund-1920x1280.jpg
  width:                                1920
  height:                               1280

personalization:                        false
comments:                               false
exclude_from_search:                    false
fab_menu_id:                            open_toc
scrollbar:                              false
toc:                                    true
regenerate:                             false
permalink:                              /pages/public/skeleton/multi/

resources:                              [ lightbox, rouge ]
resource_options:
  - toccer:
      collapseDepth:                    3
  - attic:
      slides:
        - url:                          /assets/image/module/attic/sigmund-1920x1280.jpg
          alt:                          Photo by Sigmund on Unsplash
          badge:
            type:                       unsplash
            author:                     Sigmund
            href:                       //unsplash.com/@sigmund
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The Asciidoc skeleton *multi-document* a helper for setting up a base file and
folder structure for multi-chapter AsciiDoc projects based on _Jekyll_
and _J1 Template_. You need *both* to use this skeleton creating AsciiDoc
documents from it.

[NOTE]
====
.Moving documents based on the skeleton

All Asciidoc Document Skeletons are fully *relocateable* and can be placed in
any subfolder of your Jekyll site.
====


// Include sub-documents (if any)
// -----------------------------------------------------------------------------
include::{documentdir}/100_chapter.asciidoc[]

include::{documentdir}/200_chapter.asciidoc[]


[role="mt-5"]
== Summary

[role="mb-7"]
Multi-chapter documents are used for more complex articles of a website. If
the number of chapters is or exceeds three for an article, it could make sense
to split a larger documents chapter-wise into separate files. This document
type is based on  *multiple* Asciidoc documents and make use of (local and
global) Asciidoc include files and attributes.
