---
title:                                  Skeleton
tagline:                                multi document
date:                                   2022-01-01 00:00:00
description: >
                                        Multi-chapter documents are used for more complex articles of a website. If
                                        the number of chapters is or exceeds three for an article, it could make sense
                                        to split larger documents chapter-wise into separate files. This document
                                        type is based on multiple Asciidoc documents and make use of (local and
                                        global) Asciidoc include files and attributes.

categories:                             [ Knowledge, Asciidoc ]
tags:                                   [ Skeleton, MultiDocument ]

robots:
  index:                                false
  follow:                               false

permalink:                              /pages/public/skeleton/multi/
regenerate:                             treu

personalization:                        false
comments:                               false
exclude_from_search:                    false

fab_menu_id:                            page_ctrl
scrollbar:                              false
toc:                                    true

resources:                              [ animate, clipboard, lightbox, rouge ]
resource_options:

  - toccer:
      collapseDepth:                    3

  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5

      slides:

        - url:                          /assets/images/modules/attics/sigmund-1920x1280.jpg
          alt:                          Photo by Sigmund on Unsplash
          alignY:                       0.3
          badge:
            type:                       unsplash
            author:                     Sigmund
            href:                       https://unsplash.com/@sigmund
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The Asciidoc skeleton *multi-document* a helper for setting up a base file and
folder structure for multi-chapter AsciiDoc projects based on _Jekyll_
and _J1 Template_. You need *both* to use this skeleton creating AsciiDoc
documents from it.

Multi-chapter documents are used for more complex articles of a website. If
the number of chapters is or exceeds three for an article, it could make sense
to split a larger documents chapter-wise into separate files. This document
type is based on  *multiple* Asciidoc documents and make use of (local and
global) Asciidoc include files and attributes.

[NOTE]
====
.Moving documents based on the skeleton

All Asciidoc Document Skeletons are fully *relocateable* and can be placed in
any subfolder of your Jekyll site.
====


// Include sub-documents (if any)
// -----------------------------------------------------------------------------
include::{documentdir}/100_chapter.asciidoc[]

include::{documentdir}/200_chapter.asciidoc[]
