---
title:                                  Digital Marketing
tagline:                                seo optimization
date:                                   2022-09-24 00:00:00
description: >
                                        SEO stands for Search Engine Optimization. SEO will improve
                                        your site to increase its visibility when people search for
                                        content, products, or services related to your business on
                                        Google, Bing, and other search engines.
                                        Unlike paid search ads, you cannot pay search engines to get higher
                                        organic search rankings. The algorithms used by search engines
                                        are designed to find relevant, authoritative pages and provide
                                        users with an efficient search experience. Optimizing your website
                                        and content can go a long way in helping your pages rank higher
                                        in search results, making them easier to find.

categories:                             [ Jekyll, Tutorial ]
tags:                                   [ Marketing, SEO ]

permalink:                              /pages/public/learn/kickstart/seo_optimization/whats_about_seo/
regenerate:                             true
comments:                               false

image:
  path:                                 /assets/images/modules/attics/1920x1280/melanie-deziel.jpg
  width:                                1920
  height:                               1280
  alt:                                  Photo by Melanie Deziel on Unsplash

resources:                              [ animate, carousel, comments, lightbox ]
resource_options:
  - attic:
      alignY:                           top
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/melanie-deziel.jpg
          alt:                          Photo by Melanie Deziel on Unsplash
          badge:
            type:                       unsplash
            author:                     Melanie Deziel
            href:                       https://unsplash.com/@storyfuel
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set page (local) attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Find here an overview on all chapters this tutorial:

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="dropcap"]
SEO stands for *Search Engine Optimization*. SEO will improve your site to
increase its visibility when people search for content, products, or services
related to your business on Google, Bing, and other search engines.

Unlike paid search ads, you cannot pay search engines to get higher organic
search rankings. The algorithms used by search engines are designed to find
relevant, authoritative pages and provide users with an efficient search
experience. Optimizing your website and content can go a long way in helping
your pages rank higher in search results, making them easier to find.

include::{includedir}/parts.asciidoc[tag=chapters_100_what_is_seo]
include::{documentdir}/100_what_is_seo.asciidoc[]

== Summarized

include::{includedir}/parts.asciidoc[tag=summarized]

=== Recap

include::{includedir}/parts.asciidoc[tag=recap_100_what_is_seo]

=== What Next

include::{includedir}/parts.asciidoc[tag=what_next_100_what_is_seo]

=== All Chapters
include::{includedir}/parts.asciidoc[tag=chapters]
include::{includedir}/parts.asciidoc[tag=chapters_100_what_is_seo]

=== Further Reading

include::{includedir}/parts.asciidoc[tag=further_reading]
include::{includedir}/parts.asciidoc[tag=further_reading_100_what_is_seo]
