---
title:                                  Impress
tagline:                                Legal Information

date:                                   2020-10-23
#last_modified:                         2023-01-01

description: >
                                        J1 Template is a Bootstrap V5 website template for the static
                                        site generator Jekyll.
                                        The content and works published on this website are governed by the copyright
                                        laws of Germany. Any duplication, processing, distribution, or any form of
                                        utilization beyond the scope of copyright law shall require the prior written
                                        consent of the author or authors in question.

categories:                             [ Site ]
tags:                                   [ Impress ]

robots:
  index:                                false
  follow:                               false

image:
  path:                                 /assets/images/modules/attics/1920x1280/j1-starter-mockup-1.jpg
  width:                                1920
  height:                               1280

sitemap:                                false
exclude_from_search:                    true
fab_menu_id:                            default
comments:                               false
toc:                                    false
regenerate:                             false
permalink:                              /pages/public/legal/en/impress/

resources:                              [ animate ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/j1-starter-mockup-1.jpg
          alt:                          J1 Starter Mockup
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:eu-region:                             true
:legal-warning:                         false
//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="none" %}

ifeval::[{legal-warning} == true]
WARNING: This document *does not* constitute any *legal advice*. It is
highly recommended to verify legal aspects and implications.
endif::[]

// NOTE
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// Ist ein Impressum gesetzlich vorgeschrieben?
// Ein Impressum ist auf allen kommerziellen Websites, die im
// deutschsprachigen Raum veröffentlicht werden, gesetzlich vorgeschrieben
// (Deutschland, Österreich und der Schweiz). Dies gilt unabhängig davon,
// ob die Website über eine .de-Top-Level-Domain veröffentlicht wird oder nicht.
//
// Wenn Sie lediglich einen persönlichen Blog ohne Werbung haben und kein
// Geld damit verdienen, ist das Impressum nicht erforderlich.


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
The content and works published on this website are governed by the copyright
laws of Germany. Any duplication, processing, distribution, or any form of
utilization beyond the scope of copyright law shall require the prior written
consent of the author or authors in question.

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
ifeval::[{eu-region} == true]
.Postal address
----
  <your-postal-address>
----
endif::[]

.Contact
[source, text]
----
  webmaster@<your.domain>
----

ifeval::[{eu-region} == true]
.Responsible for the content according to § 18 Abs. 1 MStV:
----
  <your-postal-address>
----
endif::[]
