---
title:                                  Cookies
title_extention:                        Good To Know About Cookies
tagline:                                About Cookies

#date:                                  2023-01-01
#last_modified:                         2023-01-01

categories:                             [ Technology ]
tags:                                   [ Cookies ]

image:
  path:                                 /assets/images/modules/attics/cookies-1920x1200.jpg
  width:                                1920
  height:                               1280
  alt:                                  Cookies - Good to know

group:                                  Featured
series:                                 Featured

#tts:                                    false
fab_menu_id:                            open_toc
comments:                               false
regenerate:                             false

resources:                              [ animate ]
resource_options:
  - attic:
      padding_top:                      600
      slides:
        - url:                          /assets/images/modules/attics/cookies-1920x1200.jpg
          alt:                          Photo by Miroslava on Unsplash
          badge:
            type:                       unsplash
            author:                     Miroslava
            href:                       https://unsplash.com/@miroslava
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

// Additional Asciidoc page attributes goes here
// -----------------------------------------------------------------------------
// :page-imagesdir: {{page.images.dir}}

// Place an excerpt at the most top position
// -----------------------------------------------------------------------------
[role="dropcap"]
Cookies can be used for various purposes, such as tracking user behavior,
remembering login credentials, and personalizing the user experience.

Providing clear and transparent information about using cookies by website
operators helps users understand how their data is used and allows them to
make better choices about their privacy.

excerpt__end

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mdi:clock-time-five-outline[24px, md-gray mr-2 mt-4]
*3-5 Minutes* to read

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== What are Cookies

HTTP header cookies, or short cookies, are a small data files that a website
asks your browser to create on your computer or mobile device. A cookie allows
the website to store your actions or preferences over time.

All modern browsers support cookies. However, users can configure a browser
to decline them. Moreover, all users can delete all or selected cookie files 
whenever they like.

Find below how cookies are typically used for.

[role="mt-4"]
=== General

In general, cookies are used to remember a vistors personal preferences.

[role="mt-4"]
=== Identification

Cookies allows to identify users, on return for example.

[role="mt-4"]
=== Support

The data stored in cookies can help users to complete tasks without
re-entering the same information when visiting the site later.

[role="mt-4"]
=== Tracking

Cookies can also be used for online behavioral target advertising and to
show innformation relevant to something that users searched for in the past.
The webserver supplying the webpage can store a cookie on the users
computer or mobile device to store such personal preferences.


[role="mt-5"]
== Types of Cookies

Cookies let websites remember you: for example your logins or purchases.
But they can also be a treasure trove of private info for criminals to
spy on.

In general, cookies can't infect computers with viruses or other type of
malware. However, some cyberattacks can hijack cookies and enable access to
your browsing sessions. The danger lies in their ability to track individuals'
browsing histories. Web browser manufacturers introduced many security
functions to minimize attack risks.

A cookie can be classified by its lifespan and the website to which it
belongs.

[role="mt-4"]
=== Lifespan

Cookies classified by lifespan are either a:

Session cookie::
Session cookies gets automatically deleted when the user closes the
web browser and all open window tabs.

Persistent cookie::
A persistent cookie remains on the user's computer/device for a
pre-defined period of time; for a year at the maximum.

[role="mt-4"]
=== Website

The domain classifies cookies, the web address to which it belongs is
either of:

First-party cookie::
First-party cookie cookies are set by the webserver of the visited page
and share the same domain you're visiting. These are generally safer, as
long as users are browsing reputable websites or ones that have not been
compromised.

Third-party cookies::
Third-party cookies are stored by a *different* domain to the visited page.
This can happen when the webpage references a file located outside its domain.
Third-party cookies let advertisers or analytics companies track the user's
browsing history across the web on any sites that contain their ads.


[role="mt-5"]
== Security

Without cookies, the Web would not work as it does today. However, since the
mid 90ies when Cookies were introduced, the web changed quite a lot, and so
did the attack methods on web applications.

[role="mb-4"]
A well-known attack method is known as cross-site request forgery or short
CSRF. A *CSRF* is an attack that forces an end user to execute unwanted
actions. A cookie may play a role in such scenarios, but they are not
generally unsafe.

[TIP]
====
If you like, read more about on a CRSF attack on the page
link:{url-owasp-attacks--csrf}[OWASP, {browser-window--new}].
====


[role="mt-5"]
== Control

Users can take control when cookies are used or not. You can delete all
cookies that are already on your computer, and you
can set most browsers to prevent them from being placed.

[role="mb-4"]
If you do this, however, you may have to manually adjust some preferences
every time you visit a site, and some services and functionalities may not
work.

[TIP]
====
For more information how cookies are used, visit the page
link:{url-about-cookies--home}[AboutCookies, {browser-window--new}].
====
