---
title:                                  J1 Theme
title_extention:                        About the Template
tagline:                                About the Template

#date:                                  2023-01-01
#last_modified:                         2023-01-01

categories:                             [ Jekyll ]
tags:                                   [ Theme ]

image:
  path:                                 /assets/images/modules/attics/1920x1280/j1-starter-mockup-1.jpg
  width:                                1920
  height:                               1280
  alt:                                  J1 Starter Mockup

group:                                  Featured
series:                                 Featured

#tts:                                    false
fab_menu_id:                            open_toc
comments:                               false
regenerate:                             false

resources:                              [ animate ]
resource_options:
  - attic:
      padding_top:                      600
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/j1-starter-mockup-1.jpg
          alt:                          J1 Starter Mockup
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:badges-enabled:                        false
:url-codinghorror--understanding-mvc:   https://blog.codinghorror.com/understanding-model-view-controller

// Place an excerpt at the most top position
// -----------------------------------------------------------------------------
[role="dropcap"]
J1 Template is a Bootstrap V5 website template for the static site generator
Jekyll.

The Theme J1 has been developed to create simple but fully configurable
websites. Jekyll One is a full-featured Theme for Jekyll to create modern
websites for free.

excerpt__end

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mdi:clock-time-five-outline[24px, md-gray mr-2 mt-4]
*2 Minutes* to read

ifeval::[{badges-enabled} == true]
{badge-j1--license} {badge-j1--version-latest} {badge-j1-gh--last-commit} {badge-j1--downloads}
endif::[]

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== Background
Many large companies today, like {url-docker--docs}[Docker, {browser-window--new}]
are using template-based systems to create their documentation web sites. Or
like {url-oreilly-atlas--home}[Atlas, {browser-window--new}] a writers platform
for books or extensive documentation created and managed by the publishing
company _O'Reilly._

[role="mb-4"]
All these platforms are technically different, but they share common ideas:

* the layout of all content is based on a standard skeleton but
  separated from the content
* content is written using a neutral meta-language
* the final output is not predefined
* the result is automatically generated by engines

[role="mt-4"]
To make these real, a lot of things are to be managed. The approaches of
Docker or O'Reilly points to a possible solution: a template system based
on _Bootstrap_ for the CSS framework, and _Jekyll_ or _Liquid_ for the core
engines, and finally _Asciidoc_ for a neutral meta-language writing content.

[role="mt-5"]
== Next steps

[role="mb-4"]
The next thought comes to my mind. Why developing a toolset for only
document servers? Documentation webs of today are complex websites. Some
features used for general web design may be not needed for documentation
systems, but a lot of components are required that are wanted in general:

* a powerful CSS and Javascript framework
* a modular approach for dynamic content and apps
* a configuration system to separate content from the layout and to automate
  creation processes following the development pattern
  link:{url-codinghorror--understanding-mvc}[Model–View–Controller, {browser-window--new}].

[role="mt-4"]
A plan was made in 2016, based on Jekyll V3 and Bootstrap V3, to create a
template-based robot system that can be used for all types of websites, for
all standard formats to create digital content.

[role="mt-5"]
== Today

[role="mb-4"]
I was too optimistic about how long it would take to build such a system:

* easy to use by developers and non-technical people
* modular, powerful and stable
* supporting modern design based on HTML V5 and Bootstrap V5
* usable on common computer hardware
* fully responsible on all devices
* entirely usable on PCs locally as well as on powerful remote systems
  on the Internet

[role="mt-4"]
It took me ages. Now in 2023, I can present the latest version of J1 Template
for the public. Hopefully, most of the objectives I had on my mind are
achieved.

Happy Jekylling!
