---
title:                                  Welcome to Jekyll
tagline:                                Websites For Everyone
#date:                                  2023-09-12
#last_modified:                         2023-01-01

categories:                             [ Jekyll, Featured ]
tags:                                   [ Post, Template ]

image:
  path:                                 /assets/images/modules/attics/katie-moum-1920x1280.jpg
  width:                                1920
  height:                               1200
  alt:                                  Jekyll for Everyone

group:                                  Featured
series:                                 Featured
regenerate:                             false

resources:                              [ animate ]
resource_options:
  - attic:
      opacity:                          0.5
      slides:
        - url:                          /assets/images/modules/attics/katie-moum-1920x1280.jpg
          alt:                          Photo by Katie Moum on Unsplash
          alignY:                       0.3
          badge:
            type:                       unsplash
            author:                     Katie Moum
            href:                       https://unsplash.com/@katiemoum
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

// Place an excerpt at the most top position
// -----------------------------------------------------------------------------
[role="dropcap"]
A static site serves the content straight to the user as it is stored on
the server-side.

Contrary to WordPress, which uses a database to load dynamic content, a
static site will display the content immediately as it will directly load
the HTML files from the server.

excerpt__end

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="mb-5"]
All you’re doing at the end of the day is writing your content, and the J1
Template does all the tricky things: putting out HTML, Javascript, and CSS.
As a result, the site creation process gets out of your way.

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
== What is a static site?

A static site serves the content straight to the user as it is stored on
the server-side. To put it in another way, in opposition to WordPress
which use a database to load dynamic content, a static site will display
the same content to every user as it will directly load the HTML files
on the server.

A static site serves the content straight to the user as it is stored on
the server-side. In opposition to WordPress, which uses a database to load
dynamic content, a static site will display the same content to every user
as it will directly load the HTML files on the server.

In the last few years, static sites have greatly increased in popularity.
This surge is primarily due to advances in developer tools (languages and
libraries) and a stronger desire among businesses to optimize website
performance beyond the limits of a database-driven site.

=== What's different?

A dynamic website uses a database and PHP/MySQL to generate the content of
a page when a user requests it. For example, building a website using
WordPress CMS will result in having a dynamic Website.

Static sites can be written almost exclusively in HTML and serve a fixed
set of data that renders the same for every site visitor. Static sites use
server-side rendering to serve pre-built HTML, CSS, and JavaScript files to
a web browser. Dynamic sites operate in a completely different way by
leveraging HTML and CSS as well as server-side scripting languages like PHP
to build webpages on the fly and serve different content to each site
visitor.

=== Why use a static site?

What are the advantages of a static website over a dynamic site?
You may be wondering *Why should I build a static site when I could do the
same by using WordPress?*. Well, having a database implies a lot of downsides.
Here come the main advantages of using a static site over a dynamic
one.

Performance::
*The better performance and a crazy fast load time*.
One of the main advantages of using a static site is the fact that
it is crazy fast to load. Indeed, when the user requests a page, there is
no need to request a database and various files to generate the
page itself as all the content is already placed in a one and only file:
an HTML one. That’s why by using a static site, you will get a boost in
your loading time that will provide a great user experience for the
internauts. Moreover, we know that more and more people are surfing the
web using their smartphones with, sometimes, poor internet connections.
That’s why having fast loading times will participate in making your
website mobile-friendly.

Security::
*Having a static website: say goodbye to hacking and security issues*.
Are you tired of getting WordPress notifications about security issues and
updates every week? No worries, as a static site has no database, there are
close to no hack possible compared to a WordPress website. Indeed, your
site will have way fewer footprints and security issues since it will
only load plain HTML and CSS files. The security gain in having a static
website is one of the main reasons why many famous brands switch to a
static site instead of having their website on Drupal or WordPress.

Hosting::
*Building a static site and hosting: you will save you money*.
Using a static site, you will only have most of the time only HTML and CSS
files to host. This kind of file is super light which also means that you
will not need a powerhouse hosting to have a static site up and running.
Moreover, if your traffic suddenly increases, your site will not go down,
contrary to a dynamic site that should request the database each time
for each user.

Control::
*You're the master*. You were using a CMS means, giving control over your
site to others. Simple like this.

== Why use a site generator?

Working with pure HTML files is annoying; senseless today. Indeed, if you need
to make a modification on your *self-managed* pages, you have to manually
change every file. That's monkey's work from the early days of static websites.
If your site comes with ten pages, it can be manageable but imagine if your
site is providing 100+ pages or the blog planned for hundreds of articles?

Using a static site generator will solve this issue as it separates the
content and the Template. To say it another way, by using a static site
generator, you will only need to make the modification once, and the
generator will apply it to all your pages.

=== Why Jekyll?

As the popularity of static sites is growing, there are plenty of static
site generators available on the market. The more famous is Jekyll,
Middleman and Hugo. Each one has its own specificities and may suits you
better depending on the programming languages you already are familiar with.
Which static site generator should I use?

When I decided to go for a blog based on a static web, I personally
choose Jekyll as for me. It's a well-known static site generator, good support
in case of trouble, and the software gets regularly updated. This website is
powered by Jekyll. For good reasons.


== Automatically generated posts

You’ll find this post in your `_posts` directory. Go ahead and edit it and
re-build the site to see your changes. You can rebuild the site in many
different ways, but the most common way is to run `jekyll serve`, which
launches a web server and auto-regenerates your site when a file is updated.

Jekyll requires blog post files to be named according to the following format:

`YEAR-MONTH-DAY-title.MARKUP`

Where `YEAR` is a four-digit number, `MONTH` and `DAY` are both two-digit
numbers, and `MARKUP` is the file extension representing the format used in
the file. After that, include the necessary front matter. Take a look at the
source for this post to get an idea about how it works.

Jekyll also offers powerful support for code snippets:

[source, ruby]
----
def print_hi(name)
  puts "Hi, #{name}"
end
print_hi('Tom')
#=> prints 'Hi, Tom' to STDOUT.
----

Check out the https://jekyllrb.com/docs/home[Jekyll Docs, {{browser-window--new}}]
for more info on how to get the most out of Jekyll. File all bugs amd feature
requests at https://github.com/jekyll/jekyll/issues[Jekyll Github Project, {{browser-window--new}}].
If you have questions, you can ask them on
https://talk.jekyllrb.com/[Jekyll Talk, {{browser-window--new}}].
